### ISSUE TITLE
Documentation improvement (Suggestion)

### ISSUE THREAD

**Issue by jpuntomarcos** [Illumina/SpliceAI#100]
Hi,

Thanks for the tool you have developed. Just a suggestion: it would be useful to explain that [annotations](https://github.com/broadinstitute/SpliceAI-lookup/tree/master/annotations) from the SpliceAI-lookup project can be used for the spliceAI package (option -A) to obtain results for **all** transcripts, along with the NM/ENST ids, which is very useful.

Regards :)

**Comment by kishorejaganathan** [comment]
Will add it shortly, thanks for the pointer!
