### ISSUE TITLE
output missing for some variants

### ISSUE THREAD

**Issue by mvheetve** [Illumina/SpliceAI#101]
Hi guys,

a bit puzzled by my output. I'm annotating WGS data using SpliceAI and for some variants I have missing output, but I can't link it to chromosome ends or another reason why predictions would not be made. Here's an example from my output:

`chr7 33132997 G T T|BBS9|0.00|0.00|0.00|0.00|324|4|999|70`
`chr7 33133278 C T T|BBS9|0.00|0.00|0.00|0.00|43|-277|-184|831`
`chr7 33133792 G T T|BBS9|0.00|0.00|0.00|0.00|21|304|200|-725`
`chr7 33133933 G T T|BBS9|0.00|0.00|0.00|0.00|-956|163|-2|-866`
`chr7 33134184 G A A|BBS9|0.00|0.00|0.00|0.00|-88|-450|-8|-417`
`chr7 33134215 ATTTTT AT AT|BBS9|.|.|.|.|.|.|.|.`
`chr7 33134770 C A A|BBS9|0.00|0.00|0.00|0.00|-152|-674|606|815`
`chr7 33136262 C A A|BBS9|0.00|0.00|0.00|0.00|-317|6|-196|34`
`chr7 33137135 G A A|BBS9|0.00|0.00|0.00|0.00|975|-121|-839|100`

Can you maybe explain to me why there are lines like `chr7 33134215 ATTTTT AT AT|BBS9|.|.|.|.|.|.|.|.` in my output, while predictions for surrounding variants appear normal? 

The command I'm using is:

`spliceai -I /path/to/input/vcf -O path/to/output/vcf -D 1000 -R /path/to/hg38.fa -A grch38` with version 1.3. 

Regards
Mattias

**Comment by kishorejaganathan** [comment]
This is because SpliceAI does not annotate variants where both ref and alt alleles have length greater than 1.
