### ISSUE TITLE
dual variants

### ISSUE THREAD

**Issue by zyh4482** [Illumina/SpliceAI#102]
Hi. 
In case a sample has two neighboring mutations within a 50bp window of one gene, how to measure the splicing alteration? The model input a nucleotide sequence with only one mutation.  It seems impossible to apply for such purpose?

**Comment by kishorejaganathan** [comment]
Hi,
Unfortunately, the current tool only can annotate one variant at a time. So you will have to individually/independently score the two variants. However, if you really want to predict splicing changes keeping in mind interactions, you can look into FAQ#3, which is a script for sequence input -> splicing probability output. Here, you can pass the reference sequence to get reference splicing probabilities and an alternate sequence with both the variants inserted simultaneously to get alternate sequence probabilities, and subtract the two to get delta scores. Note: you might want to use a context length of 10101 here (to mimic https://github.com/Illumina/SpliceAI/blob/b083eb5f8f0d773c7c977aac0c45880d47ca18b7/spliceai/utils.py#L96).

Regards,
Kishore
