### ISSUE TITLE
Score for some mutations in Illumina files make zero biological sense

### ISSUE THREAD

**Issue by BJWiley233** [Illumina/SpliceAI#103]
We downloaded the `spliceai_scores.raw.snv.hg38.vcf.gz` and `spliceai_scores.raw.indel.hg38.vcf.gz` files from Illumina's webpage.  I am interested why some scores, in the light of most biological studies of canonical splice sequences, makes no sense.  For instance for the "major" U2-dependent spliceosome for U2-introns (See [Figure1](https://wires.onlinelibrary.wiley.com/doi/10.1002/wrna.1141)) the canonical -2 to +2 sequence for 3' acceptors (splice sites are defined by the introns not the exons) is `[CTA]AG|GT[N]` where the `|` represents the splice site and `[CTA]` indicates either C or T or A in that descending order and `[N]` means equal probability of any base.  So my question for position chr11:72229088 for hg38 it indicates that an A>G mutation and +1 position 72229089 is used as a splice acceptor increases by 1.0 are you referring that the probability of the new splice site being for -2 to +2 (positions [72229089-72229092](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr11%3A72229089%2D72229092&hgsid=1334324591_trJAUBjRIDDsJW3WX1zjLIP0UctN)) and sequence `GT|GC` would be the new splice site?

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
11	72229088	.	A	C	.	.	SpliceAI=C|INPPL1|0.05|0.98|0.00|0.00|46|2|-40|2
11	72229088	.	A	G	.	.	SpliceAI=G|INPPL1|1.00|0.98|0.00|0.00|1|2|0|-40
11	72229088	.	A	T	.	.	SpliceAI=T|INPPL1|0.10|0.98|0.00|0.00|46|2|-40|2
```

**Comment by BJWiley233** [comment]
Instead of for the splice acceptor site for this line being a +1 base location for increase probability of 1.0 of being a splice acceptor site:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
11	72229088	.	A	G	.	.	SpliceAI=G|INPPL1|1.00|0.98|0.00|0.00|1|2|0|-40
```

It should really be a -1 as in below making chr11:72229087 (72229088-1) is used as a splice acceptor increases by 1.0. Then with this A>G mutation at position chr11:72229088, your new -2 to +2 splice site is as follows `AG|GT` which is (drumroll please ............) the CANONICAL 3' splice acceptor site sequence!

**Comment by BJWiley233** [comment]
Please read https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3119917/

"Indeed, ∼45 proteins are recruited to the human spliceosome as part of the spliceosomal snRNPs, whereas non-snRNP proteins comprise the remainder"

"For example, yeast precatalytic B complexes contained only ∼60 proteins (compared to ∼110 in humans and flies), including essentially all U1, U2, and tri-snRNP proteins plus proteins of the nineteen complex (NTC) and mRNA retention and splicing (RES) complex"

**Comment by kishorejaganathan** [comment]
Thank you for the message, we will keep this in mind for the next iteration. In the previous iteration, the model was trained to assign a high probability to the first and last base of an exon (acceptor and donor probability respectively), which is reflected in these results. Switching it to the first and last base of an intron (for donor and acceptor probability) makes more sense.
