### ISSUE TITLE
SpliceAI scores pre-calculation with in silico mutagenesis 

### ISSUE THREAD

**Issue by SIJAE-WOO** [Illumina/SpliceAI#104]
Hi,
I want to make SpliceAI scores pre-calculated files with in silico mutagenesis like yours for updated reference genomes and annotations. Could you share your scripts when you used for running SpliceAI scores pre-calculation? And, I'm curious how long the pre-calculation running time!

Regards,
Sijae

**Comment by kishorejaganathan** [comment]
Hi Sijae,
The pre-calculations take a lot of time, so I would probably not recommend doing this from scratch. That is, you can just look at the variants/genes that are missing in the current annotations and only score them. There are no special scripts, you can just use the SpliceAI package. All you have to do is create a VCF with all the variants that you want to score. For parallel processing, you can split the VCFs into multiple short ones and send them as separate jobs.

Regards,
Kishore
