### ISSUE TITLE
Working with genes on - strand

### ISSUE THREAD

**Issue by Abhinav-Mittal** [Illumina/SpliceAI#105]
How to work with gene sequences from -ve strand? For eg. SCN1A gene. In the output vcf, it seems as if donor-acceptor scores and positions need to interchange.

**Comment by kishorejaganathan** [comment]
If DP (delta position) is -X, then the position where splicing changes is "variant position - X". This is the position in the DNA, so this will be upstream of the variant in the RNA if the gene is in the +ve strand, and downstream if the gene is in the negative strand.
