### ISSUE TITLE
Why do i got two results for one postion?

### ISSUE THREAD

**Issue by genegogo2019** [Illumina/SpliceAI#107]
Dear:
         my -D was set at 4999. What is your suggestion for this kind of result? Thank you!

chr1,1730364,1730364,-,T,"intron","GNB1","NM_001282538:exon4:c.514+7550->A;NM_001282538:exon5:c.130+5494->A;NM_001282538:exon6:c.131-5614->A;NM_001282539:exon5:c.267+7550->A;NM_001282539:exon6:c.430+5494->A;NM_001282539:exon7:c.431-5614->A;NM_002074:exon6:c.267+7550->A;NM_002074:exon7:c.430+5494->A;NM_002074:exon8:c.431-5614->A",.,.,"0.995187833121982","0.00481167835276296","4.8852525544842e-07","G protein subunit beta 1","FUNCTION: Guanine nucleotide-binding proteins (G proteins) are involved as a modulator or transducer in various transmembrane signaling systems. The beta and gamma chains are required for the GTPase activity, for replacement of GDP by GTP, and for G protein- effector interaction.; ",".",".",".",".","0.86155","0.25991","-0.317668748","31.45789101","0.82137","0.01624","1p36.33","intron","ENSG00000078369","ENST00000378609:exon6:c.267+7550->A;ENST00000378609:exon7:c.430+5494->A;ENST00000378609:exon8:c.431-5614->A;ENST00000439272:exon5:c.228+7550->A;ENST00000439272:exon6:c.391+5494->A;ENST00000439272:exon7:c.392-5614->A;ENST00000434686:exon7:c.267+7550->A;ENST00000434686:exon8:c.430+5494->A;ENST00000434686:exon9:c.431-5614->A",.,.,"intron","GNB1","uc001aif.3:exon6:c.267+7550->A;uc001aif.3:exon7:c.430+5494->A;uc001aif.3:exon8:c.431-5614->A;uc009vky.3:exon4:c.484+7550->A;uc009vky.3:exon5:c.130+5494->A;uc009vky.3:exon6:c.131-5614->A",.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,0.3015,0.3996,0.2984,0.3055,0.2656,0.1582,.,0.2336,0.1747,0.3996,0.3960,0.3142,0.3219,0.3970,0.3980,.,0.3720,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,"rs34414397",.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,"chr1     1730364                              rs34414397       C       CT      680.73  .       AC=1,1;AF=0.5,0.5;AN=2;BaseQRankSum=0.316;ClippingRankSum=0;DB;DP=31;ExcessHet=3.0103;FS=3.15;MLEAC=1,1;MLEAF=0.5,0.5;MQ=59.33;MQRankSum=-0.3;QD=23.47;ReadPosRankSum=0.771;SOR=0.105;SpliceAI=CT|GNB1|0.00|0.00|0.01|0.00|-562|-2506|-1784|-1135,CTT|GNB1|0.00|0.00|0.00|0.00|-1731|-562|-1784|998       GT:AD:DP:GQ:PL  1/2:2,11,16:29:99:718,344,294,213,0,198"
chr1,1730364,1730364,-,TT,"intron","GNB1","NM_001282538:exon4:c.514+7550->AA;NM_001282538:exon5:c.130+5494->AA;NM_001282538:exon6:c.131-5614->AA;NM_001282539:exon5:c.267+7550->AA;NM_001282539:exon6:c.430+5494->AA;NM_001282539:exon7:c.431-5614->AA;NM_002074:exon6:c.267+7550->AA;NM_002074:exon7:c.430+5494->AA;NM_002074:exon8:c.431-5614->AA",.,.,"0.995187833121982","0.00481167835276296","4.8852525544842e-07","G protein subunit beta 1","FUNCTION: Guanine nucleotide-binding proteins (G proteins) are involved as a modulator or transducer in various transmembrane signaling systems. The beta and gamma chains are required for the GTPase activity, for replacement of GDP by GTP, and for G protein- effector interaction.; ",".",".",".",".","0.86155","0.25991","-0.317668748","31.45789101","0.82137","0.01624","1p36.33","intron","ENSG00000078369","ENST00000378609:exon6:c.267+7550->AA;ENST00000378609:exon7:c.430+5494->AA;ENST00000378609:exon8:c.431-5614->AA;ENST00000439272:exon5:c.228+7550->AA;ENST00000439272:exon6:c.391+5494->AA;ENST00000439272:exon7:c.392-5614->AA;ENST00000434686:exon7:c.267+7550->AA;ENST00000434686:exon8:c.430+5494->AA;ENST00000434686:exon9:c.431-5614->AA",.,.,"intron","GNB1","uc001aif.3:exon6:c.267+7550->AA;uc001aif.3:exon7:c.430+5494->AA;uc001aif.3:exon8:c.431-5614->AA;uc009vky.3:exon4:c.484+7550->AA;uc009vky.3:exon5:c.130+5494->AA;uc009vky.3:exon6:c.131-5614->AA",.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,0.0976,0.3475,0.0978,0.0972,0.0872,0.0206,.,0.3475,0.3026,0.1080,0.1102,0.0487,0.1368,0.3545,0.3325,.,0.2860,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,"rs747350293",.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.,"chr1                1730364  rs34414397      C       CTT     680.73  .       AC=1,1;AF=0.5,0.5;AN=2;BaseQRankSum=0.316;ClippingRankSum=0;DB;DP=31;ExcessHet=3.0103;FS=3.15;MLEAC=1,1;MLEAF=0.5,0.5;MQ=59.33;MQRankSum=-0.3;QD=23.47;ReadPosRankSum=0.771;SOR=0.105;### **`SpliceAI=CT|GNB1|0.00|0.00|0.01|0.00|-562|-2506|-1784|-1135,CTT|GNB1|0.00|0.00|0.00|0.00|-1731|-562|-1784|998       GT:AD:DP:GQ:PL  1/2:2,11,16:29:99:718,344,294,213,0,198"`**

**Comment by MattCloward** [comment]
You get two results, one for each alternate allele. In this case, the first allele is "CT" and the second is "CTT." Hope that helps!

**Comment by genegogo2019** [comment]
> You get two results, one for each alternate allele. In this case, if I am interpreting this correctly, the first allele is "CT" and the second is "CTT." Hope that helps!

Thanks for your reply. But it is more convenient if it separated into two lines for two alternatives. The results were combined in a line made it difficult in separating them later.
