### ISSUE TITLE
TensorFlow binary was not compiled to use: SSE4.1 SSE4.2

### ISSUE THREAD

**Issue by dmcgoldrick** [Illumina/SpliceAI#11]
Hi SpliceAI --

Thanks for the code but I am new to this application and need some assistance.

After running an installed spliceai on CentOS6 OS I get this message

------------------------------------------------------------------------------------------------------------------------------
TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 ... UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
 tensorflow/1.4.1
-------------------------------------------------------------------------------------------------------------------------------

I am not understanding the warning completely, do I need to modify my installation for the CPUs I have? I get an output but not a complete output and it ran overnight.
 
Can you recommend a strategy for CentOS6 HPC users and perhaps give a typical runtime for this? I am not sure my implementation is working yet. :-/

Daniel

**Comment by kishorejaganathan** [comment]
Dear Daniel,
You can ignore the UserWarning, it is a harmless one. Here are some things that you could do to make sure you have installed everything correctly:
- If you use the git clone approach to install SpliceAI, go into the SpliceAI directory (where the setup.py file resides) and do python setup.py test. If all tests pass successfully, you are good to go.
- We have provided an example input and output file in the examples folder. Use the input file as the input and make sure you can produce the output file.

SpliceAI can annotate around 30k variants per hour on a GPU and around 4k variants per hour on a CPU. The power of SpliceAI comes from the massive amount of computations it does, so the throughput bottleneck is expected. To alleviate this issue, we have precomputed the scores for all possible SNVs within genes using our compute infrastructure and released the scores to the public (see README of the github page for the link to download this dataset). So, the strategy we recommend is to use the tool to annotate INDELs, and use the file with the precomputed scores as a look up table for SNVs.

**Comment by dmcgoldrick** [comment]
ok -- 
Thanks for the quick assist and advice.
Daniel
