### ISSUE TITLE
Scoring splicing probability of novel splice sites

### ISSUE THREAD

**Issue by aleighbrown** [Illumina/SpliceAI#110]
Hello, 

I'm interested scoring the acceptor and donor probability of novel intronic splice sites we've discovered in our sequencing data.

Based on the FAQ about scoring custom sequences I've written the following function to return the splicing probabilities in the region around the novel splice site, as well as the site itself. This would be on human genome, hg38

```
def run_spliceai(input_sequence):
        # Replace this with your custom sequence

    context = 10000
    paths = ('models/spliceai{}.h5'.format(x) for x in range(1, 6))
    models = [load_model(resource_filename('spliceai', x)) for x in paths]
    x = one_hot_encode('N'*(context//2) + input_sequence + 'N'*(context//2))[None, :]
    y = np.mean([models[m].predict(x) for m in range(5)], axis=0)

    acceptor_prob = y[0, :, 1]
    donor_prob = y[0, :, 2]
    
    return acceptor_prob, donor_prob

```

This returns vectors for each nucleotide in the input_sequence of splicing probility. However, what I'm not sure about is how the length or context around the splicing site affects the scores return. 

For example, for now I include the genomic sequence of the novel splice site +/- 20 bp. 

Does the input sequence length matter?
What does the context = 1000 do here? 

thank you!

**Comment by kishorejaganathan** [comment]
In the case of custom sequences, the main role of context is just to make sure there is enough padding on either side of the position of interest (spliceAI requires 10K context positions to make a prediction, so when true context doesn't exist for that long (esp. if your sequence is short) we use Ns on either side to get the required context length). In your case, given that you're getting sequences from hg38, you can just provide a very long input sequence. That is, if you're interested in splicing probabilities for 100 positions, let input sequence be 5000 + 100 + 5000 nucleotides. That is a more precise implementation for your setup.

**Comment by aleighbrown** [comment]
Thank you! this makes it more clear
