### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'typing'

### ISSUE THREAD

**Issue by udp3f** [Illumina/SpliceAI#114]
Hi,
I installed the tool with conda (I have miniconda 3 installed) and the installation seemed neat. However, running the tool gives me an ImportError (python in use is 3.7) "ImportError: cannot import name 'Literal' from 'typing'". The pandas version in use is pandas-1.5.2. Any suggestions, how I can get past this error.
Thanks

**Comment by kishorejaganathan** [comment]
Do you know which package is causing this error? If it is pandas, then downgrading it should solve the issue. Quick googling suggests that you can import Literal from typing only from python 3.8, so one of the packages that was installed is too advanced for this python version.

**Comment by udp3f** [comment]
Yes, the pandas package was causing the error. I downgraded it to pandas 1.3 and it works now. Thank you :)
