### ISSUE TITLE
zsh: command not found: spliceai

### ISSUE THREAD

**Issue by cycan8130** [Illumina/SpliceAI#116]
Hi!
I just continue to have this issue when running SpliceAI in terminal. 
Thank you so much!

**Comment by kishorejaganathan** [comment]
This suggests you have not installed SpliceAI. Are you sure you have installed it?

**Comment by cycan8130** [comment]
<img width="685" alt="Screen Shot 2023-03-04 at 15 35 09" src="https://user-images.githubusercontent.com/126927799/222875871-d173c9b5-1934-4599-9e7c-2b96cddd8a0c.png">

I think I have installed it as I pasted the command(git clone https://github.com/Illumina/SpliceAI.git
cd SpliceAI
python setup.py install)  it just direct me to the SpliceAI file.

**Comment by kishorejaganathan** [comment]
Hi, can you try other modes of installation (like pip install spliceai). And if you have already tried it, maybe that is why the git clone method is claiming that the directory already exists. If nothing works out, I'd recommend downloading the files with pre-computed scores and using it as a look up table.

**Comment by sruthisrini** [comment]
Hi @cycan8130, it is because of the permission access. Please try using sudo, "sudo python setup.py install" . Then it should work.
