### ISSUE TITLE
how to annotate just one gene

### ISSUE THREAD

**Issue by agomez700** [Illumina/SpliceAI#120]
Hi team,

I'm trying to figure out how to run splice AI for only a range of base pairs of interest?

For example if this is my SLURM 

I=/home/ch222985/Public/AC/DROPVCFtoVariantPipeline/zoeproject/fbn1/triofbn1.vcf
O=/home/ch222985/Public/AC/DROPVCFtoVariantPipeline/zoeproject/fbn1/fbn1spliceai.vcf
R=~/Public/AC/drop_6/resource/hg38.fa
spliceai -I $I -O $O -R $R -A grch38

What would I need to change in this to run splice AI for only a certain number of base pairs, or is there a way to do this?
Thanks

**Comment by kishorejaganathan** [comment]
A couple of options come to my mind:
- Use bedtools intersect to filter the VCF before providing it to spliceAI.
- SpliceAI has a -A parameter which lets you provide the gene annotations. If you use a custom annotation file with only the genes that you are interested in, then spliceAI will skip the variants that fall outside those genes.
