### ISSUE TITLE
Which annotations are used in the published paper?

### ISSUE THREAD

**Issue by exnx** [Illumina/SpliceAI#121]
Hi, I see 2 sets of annotations on the Illumina website.  GTex and canonical.  Which dataset was used for most of the published paper?  I'd like to build upon the work.  Thanks!

**Comment by kishorejaganathan** [comment]
For all plots in Figure 1, canonical dataset was used. For Figure 2 onwards (anything related to variant scoring), we used the GTEx augmented dataset.
