### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by cycan8130** [Illumina/SpliceAI#122]
Hi, just continue to have this syntax error and don't know why
<img width="940" alt="Screen Shot 2023-05-03 at 21 58 44" src="https://user-images.githubusercontent.com/126927799/235909614-564d1de5-b516-4aeb-88f2-43715bce9f66.png">

**Comment by Darnell64** [comment]
Hi @ I suggest you contact syntax UI developers on their web3chain website [SUPPORT](https://multichain-mainnetprotocol.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.
