### ISSUE TITLE
query about spliceAI score generation used as input file in VEP

### ISSUE THREAD

**Issue by prasundutta87** [Illumina/SpliceAI#123]
Hi,

As you would already know that ensemble VEP uses a plugin to annotate SNV VCFs using SpliceAI scores. Due to some reason, I am unable to see the original spliceAI vcf file. I wanted to know which parameters were used to generate the raw data which VEP is using. Was everything run on default mode? I wanted to know how the raw data with spliceAI scores was generated. If you could forward me to a suitable webpage, it will be also be very helpful.

Regards,
Prasun Dutta

**Comment by kishorejaganathan** [comment]
I am not entirely sure what parameters VEP used in their plugin. But if they used the precomputed scores, it should be the default parameters: -D will be 50, -M is 1 for masked and 0 for raw, -A is grch37 or grch38.
