### ISSUE TITLE
cryptic splice sites

### ISSUE THREAD

**Issue by prasundutta87** [Illumina/SpliceAI#126]
Hi,
I was just wondering what would be the best way to identify cryptic splice sites from spliceAI output. I am using the VEP spliceAI plugin. I checked this- https://github.com/Illumina/SpliceAI/issues/12, but may be this information is not added by VEP.

Regards,
Prasun

**Comment by kishorejaganathan** [comment]
To identify splice sites, you would need to use DP (delta position) annotations. There are four of them: two for donors/acceptors and two for gain/loss. For cryptic splice sites, you're mostly interested in gains. I believe they should be a part of the VEP spliceAI output. If not then you can run the github tool to annotate a VCF or download the precomputed scores (check README).

**Comment by prasundutta87** [comment]
Thanks @kishorejaganathan. I am actually using the VEP consequence in order to get cryptic splice sites. So, I have removed any variants that have a "splice acceptor variant" or "splice donor variant" as one of its consequence in addition to having a good SpliceAI score. Based on your comment, I could also put that the max SpliceAI delta score should come from DS_AG (SpliceAI_pred_DS_AG in VEP) or DS_DG (SpliceAI_pred_DS_DG in VEP). Does this make sense? 

Not sure if Delta position needs to be considered for this.
