### ISSUE TITLE
Delta position seems to be wrong for this variant

### ISSUE THREAD

**Issue by Manuel-DominguezCBG** [Illumina/SpliceAI#128]
Hi Manuel,

I’ve just used SpliceAI to investigate the following variant: (NM_004456.5(EZH2):c.1947+2dup)

`7       148508714       .       T       TA`
![image](https://github.com/Illumina/SpliceAI/assets/74112779/1a760d68-8e45-4fda-97e7-799d3beb660a)

When putting this into SpliceAI , you get the following results:

`7       148508714       .       T       TA          SpliceAI=TA|EZH2|0.00|0.00|0.04|0.79|-23|35|-23|3       GT      0/1`

This shows that there is a donor loss 3 bp downstream from the variant (due to the positive pre-mRNA position value); however, the splice donor site is 3 bp upstream from the variant. We think that we have also noticed this for other variants too.

Is this wrong or correct?

We have also use SpliceAI lookup and the results are the same

![image](https://github.com/Illumina/SpliceAI/assets/74112779/dde0daf8-855b-47b2-9f32-23cbef871a65)

As always, thanks in advance for your help.

Regards, 

Manuel

**Comment by kishorejaganathan** [comment]
Downstream in the DNA (but that becomes upstream in the mRNA because the gene is in negative strand).
