### ISSUE TITLE
Trouble to launch SpliceAI with grch37

### ISSUE THREAD

**Issue by JbaptisteLam** [Illumina/SpliceAI#132]
Hi,
After many tries I don't manage to generate results with grch37 assembly while I don't have any trouble with grch38 which I used for a while,
After parsing input and I 'm getting the first warning of tensorflow then it raise a "segmentation fault (coredumped)" error
![unnamed](https://github.com/Illumina/SpliceAI/assets/82168721/a9cb7fc9-dd9b-431f-887e-7b224e899867)

Any workaround ?

Best,

Jean-Baptiste

**Comment by JbaptisteLam** [comment]
Sorry I have forgotten my specs:
I used spliceai v1.3.1
Working in a singularity container created by a docker image

**Comment by kishorejaganathan** [comment]
Are you using the correct VCF header for grch37? If you could paste the header here along with a couple of variants that will help me advise you better.

**Comment by JbaptisteLam** [comment]
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##note=VCF file is compatible with VCFv4.3 if required by updating fileformat parameter to v4.3
##copyright=HGMD. Not for redistribution.
##source=HGMD_PRO_2021.3
##reference=GRCh37
##comment="REF and ALT sequences are both on forward strand of reference assembly"
##INFO=<ID=CLASS,Number=1,Type=String,Description="Mutation Category, https://portal.biobase-international.com/hgmd/pro/global.php#cats">
##INFO=<ID=MUT,Number=1,Type=String,Description="HGMD mutant allele">
##INFO=<ID=GENE,Number=1,Type=String,Description="Gene symbol">
##INFO=<ID=STRAND,Number=1,Type=String,Description="Gene strand">
##INFO=<ID=DNA,Number=1,Type=String,Description="DNA annotation.  The ':' (colon) in DNA HGVS descriptions have been replaced with '%3A'.  Instructions to deal with such characters with special meaning are given in Section 1.2 of the VCFv4.3 specfication.">
##INFO=<ID=PROT,Number=1,Type=String,Description="Protein annotation.  The ':' (colon), the ';' (semicolon), and the '=' (equal sign) in protein HGVS descriptions have been replaced with '%3A', '%3B', and '%3D' respectively.  Instructions to deal with such characters with special meaning are given in Section 1.2 of the VCFv4.3 specfication.">
##INFO=<ID=DB,Number=1,Type=String,Description="dbSNP identifier, build 146">
##INFO=<ID=PHEN,Number=1,Type=String,Description="HGMD primary phenotype.  The ',' (comma) in primary phenotype descriptions have been replaced with '%2C'.  Instructions to deal with such characters with special meaning are given in Section 1.2 of the VCFv4.3 specfication.">
##INFO=<ID=RANKSCORE,Number=1,Type=Float,Description="HGMD computed rankscore.  The HGMD computed rankscore is a probability of pathogenicity between 0 and 1, with 1 being most likely disease-causing compared to other HGMD entries. The score is computed using a machine learning approach, and is based upon multiple lines of evidence, including HGMD literature support for pathogenicity, evolutionary conservation (100 way vertebrate alignment), variant allele frequency and in-silico pathogenicity prediction. Scores may be used to prioritize and rank multiple HGMD variants which have been found in the same sample, so in practise refer to the tag first and then use the rankscore to rank variants in the same variant class (e.g. DM or DM? etc). This feature is under ongoing development.">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of variant described in this record">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="Description in length between REF and ALT alleles">
##contig=<ID=chr21,assembly=hg19,length=48129895>
##contig=<ID=chr2,assembly=hg19,length=243199373>
##contig=<ID=chrX,assembly=hg19,length=155270560>
##contig=<ID=chr20,assembly=hg19,length=63025520>
##contig=<ID=chrY,assembly=hg19,length=59373566>
##contig=<ID=chr1,assembly=hg19,length=249250621>
##contig=<ID=chr19,assembly=hg19,length=59128983>
##contig=<ID=chr15,assembly=hg19,length=102531392>
##contig=<ID=chr3,assembly=hg19,length=198022430>
##contig=<ID=chr6,assembly=hg19,length=171115067>
##contig=<ID=chr4,assembly=hg19,length=191154276>
##contig=<ID=chrM,assembly=hg19,length=16571>
##contig=<ID=chr5,assembly=hg19,length=180915260>
##contig=<ID=chr11,assembly=hg19,length=135006516>
##contig=<ID=chr7,assembly=hg19,length=159138663>
##contig=<ID=chr18,assembly=hg19,length=78077248>
##contig=<ID=chr8,assembly=hg19,length=146364022>
##contig=<ID=chr9,assembly=hg19,length=141213431>
##contig=<ID=chr10,assembly=hg19,length=135534747>
##contig=<ID=chr14,assembly=hg19,length=107349540>
##contig=<ID=chr16,assembly=hg19,length=90354753>
##contig=<ID=chr17,assembly=hg19,length=81195210>
##contig=<ID=chr12,assembly=hg19,length=133851895>
##contig=<ID=chr13,assembly=hg19,length=115169878>
##contig=<ID=chr22,assembly=hg19,length=51304566>
##ALT=<ID=DEL,Description="Deletion">
##bcftools_viewVersion=1.9+htslib-1.9
##bcftools_viewCommand=view -h DM_HGMD.corrected.vcf; Date=Thu Jul 27 10:36:11 2023
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Sample
chr1	949363	CS2015176	G	A	.	.	CLASS=DM;MUT=ALT;GENE=ISG15;STRAND=+;DNA=NM_005101.4%3Ac.4-1G>A;PHEN="Ulcerative_skin_lesions";RANKSCORE=0.11	GT:AD:DP	0/1:50,50:100
chr1	985175	CS207495	G	A	.	.	CLASS=DM;MUT=ALT;GENE=AGRN;STRAND=+;DNA=NM_198576.4%3Ac.4744G>A;PROT=NP_940978.2%3Ap.G1582R;DB=rs1367262797;PHEN="Congenital_myasthenic_syndrome";RANKSCORE=0.65	GT:AD:DP	0/1:50,50:100
chr1	1271896	CS200109	C	T	.	.	CLASS=DM;MUT=ALT;GENE=DVL1;STRAND=-;DNA=NM_004421.3%3Ac.1640-1G>A;PHEN="Robinow_syndrome%2C_autosomal_dominant";RANKSCORE=0.16	GT:AD:DP	0/1:50,50:100
chr1	1452795	CS2015028	A	G	.	.	CLASS=DM;MUT=ALT;GENE=ATAD3A;STRAND=+;DNA=NM_001170535.3%3Ac.384+3A>G;PHEN="Harel-Yoon_syndrome"	GT:AD:DP	0/1:50,50:100
chr1	1460672	CS1924930	G	A	.	.	CLASS=DM;MUT=ALT;GENE=ATAD3A;STRAND=+;DNA=NM_001170535.3%3Ac.1266+1G>A;DB=rs757205195;PHEN="Neurological_syndrome";RANKSCORE=0.78	GT:AD:DP	0/1:50,50:100


Here is a part of the vcf

**Comment by kishorejaganathan** [comment]
Hmm, looks alright to me. Could you try the following:
- Use a minimal header (from the examples folder of spliceai repo, and remove all metadata from the VCF in the INFO column.
- Is the error coming from a single variant? You can shorten the VCF by keeping only the first few variants and see if you still get an error. If that is the case, maybe some variants are not correct (this can happen if you use a slightly different reference and have chromosomes that are not recognized in the header or lengths don't match).

**Comment by JbaptisteLam** [comment]
Guess I manage to fix this by removing quoting in all variants and according to VCF specifications 4.3 replace all '%<int>...' by true char (semi colon and others) both in INFO field
It's working now :)

Thanks for all
