### ISSUE TITLE
Position of splice sites within an insertion

### ISSUE THREAD

**Issue by baumanale** [Illumina/SpliceAI#134]
Hello,

we are using SpliceAI regularly at our institute and recently encountered a case where more information on the resulting pre-mRNA position in insertions would be great.

The respective case is a long insertion, which led to a splice acceptor and splice donor gain within the insertion (already validated on RNA level).
([https://spliceailookup.broadinstitute.org/#variant=chr5-112800732-T-TAACAGATGGTGAGGGGAGGAGCCAAGATGGCCGAATAGGAACAGCTCCGGTCTACAGCTCCCAGCGTGAGCGACGCAGAAGACGGTGATTTCTGCATTTCCATCTGAGGTACCGGGTTCATCTCACTAGGGAGTGCCAGACAGTGGGCGCAGGCCA&hg=38&distance=10000&mask=0](https://spliceailookup.broadinstitute.org/#variant=chr5-112800732-T-TAACAGATGGTGAGGGGAGGAGCCAAGATGGCCGAATAGGAACAGCTCCGGTCTACAGCTCCCAGCGTGAGCGACGCAGAAGACGGTGATTTCTGCATTTCCATCTGAGGTACCGGGTTCATCTCACTAGGGAGTGCCAGACAGTGGGCGCAGGCCA&hg=38&distance=10000&mask=0))
![SplcieAI_example](https://github.com/Illumina/SpliceAI/assets/83640817/6cbe1450-ea9d-4cb8-be83-39a07ab78f66)

The SpliceAI lookup (and VCF created by command line SpliceAI usage) showed a very high delta score of acceptor and donor gain at position 0 (which is the insertion).
I already explained the case as an answer to an issue at SpliceAI Lookup (see last answer at [https://github.com/broadinstitute/SpliceAI-lookup/issues/31](https://github.com/broadinstitute/SpliceAI-lookup/issues/31)).

Would it be possible to get the position information within the insertion, so on the alternative sequence? Therefore, one would need the alternative sequence as “reference” for the position information instead of the wildtype sequence. Of course, that would only be useful for insertions.

Do you see any possibility of getting that information with your algorithm?

Thank you very much!

Best,
Alex

**Comment by kishorejaganathan** [comment]
Hi Alex,
The information should be easily extractable from this line https://github.com/Illumina/SpliceAI/blob/b083eb5f8f0d773c7c977aac0c45880d47ca18b7/spliceai/utils.py#L171-L176

If you do the same operation with argmax instead of max, you should know the precise location inside the insertion where the score changed.

Regards,
Kishore
