### ISSUE TITLE
All possible SNVs for grch37 

### ISSUE THREAD

**Issue by CLeib** [Illumina/SpliceAI#14]
Hello,
Is there an available file of all possible SNVs for grch37, or can you advise how to create one?
Many thanks!

**Comment by kishorejaganathan** [comment]
You should find them here: https://basespace.illumina.com/s/5u6ThOblecrh . The "all possible SNVs" file contains only those variants which have a SpliceAI score > 0.1 to keep the file size manageable. If you're interested in variants with SpliceAI score < 0.1 as well, my recommendation would be to start with the grch37.txt file in the spliceai/annotations folder (github). It contains the list of genes, their transcription start and end sites that were used to precompute the SNV scores (i.e., only the SNVs within these regions were considered). You can create a list of all possible SNVs within these positions. If you find the SpliceAI annotation in the precomputed file, then use the annotation, else set the SpliceAI score to 0 I guess (although that is not a 100% precise as we only know that it is <0.1).

**Comment by holtgrewe** [comment]
Hi, it looks like the BaseSpace folder only contains the GRCh38 sites, or am I mistaken?

**Comment by holtgrewe** [comment]
Another suggestion: Zeondo takes versioned uploads and preserves them for eternity (albeit with no easy possibility to take down files). Maybe this could complement the base space files for those of us who cannot go/have not gone cloud yet?

**Comment by bschilder** [comment]
Am I correct in assuming that `genome_scores_v1.3/spliceai_scores.raw.snv.hg19.vcf.gz` contains all SNVs, even those with a max SpliceAI score <0.1? Based on taking subsets of this file it seems like this is the case, but I want to make sure.

In contrast, `SupplementaryData/SpliceAI_supplement_v2/whole_genome_filtered_spliceai_scores.vcf.gz` only contains SNVs (and INDELS) where SpliceAI score >0.1, correct?

Thanks!, 
Brian

**Comment by kishorejaganathan** [comment]
Your assumption is correct (spliceai_scores.masked.snv.hg19.vcf.gz is the super-set of whole_genome_filtered_spliceai_scores.vcf.gz though). Please see FAQ #2 in the github README for raw vs masked.
