### ISSUE TITLE
No training configuration found in the save file, so the model was *not* compiled. Compile it manually.

### ISSUE THREAD

**Issue by Ritetsu** [Illumina/SpliceAI#144]
Hi!

I was trying to score my custom sequences with SpliceAI as follow:
```python
from keras.models import load_model
from pkg_resources import resource_filename
from spliceai.utils import one_hot_encode
import numpy as np

input_sequence = 'ACTATGGATGAAAAAGAAATATTTCTCCAACAATCATGAATTCAGCTTCCATTTCATGGAATAATCAAGAATTTTAAACATAGTACTTCTGCTACTAGGACTTGATTTTCAAGAAATACCAAAATAGCTTCACTCAGTGACCCAAGCTTTTTTCACAAATTCCATTCATAATTGCACGTCCTTACCTTAACAATAGCCTTTTTCTTATGATATTTCTCTCCCAGTTTCTTGGTTATAATTTTCACAATAATTTCCTAGAAAATAATAACAAAAAAAATGAAAGGAAAGACAGAAGTTATCGTTTGTCATTTACTTCTTCCTTTTAAACTATGTTCACCCAAAACCACAGGAAAATGTAACTGCCCTGCCAAATAAGAAATGCTGGAGTTCTCTGCCTTCCCAACAATGACAAACATTTCCTTAGCAATCTTTTATTCCTTCTTCCCCTTTCTGTTCAACGTGGTTAGCAAGAGGAAAAAAATATATACATATATATAAAAAATGTCTGAT'

context = 10000
paths = ('models/spliceai{}.h5'.format(x) for x in range(1, 6))
models = [load_model(resource_filename('spliceai', x)) for x in paths]
x = one_hot_encode('N'*(context//2) + input_sequence + 'N'*(context//2))[None, :]
y = np.mean([models[m].predict(x) for m in range(5)], axis=0)

acceptor_prob = y[0, :, 1]
donor_prob = y[0, :, 2]
```

and got:
```python
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
1/1 [==============================] - 1s 1s/step
1/1 [==============================] - 1s 938ms/step
1/1 [==============================] - 1s 911ms/step
1/1 [==============================] - 1s 898ms/step
1/1 [==============================] - 1s 897ms/step
```

My input sequence is a 510nt long DNA sequence, and there should be splice sites around position 255/256, and the acceptor_prob/donor_prob seems didn't return the right socre.
```python
np.argmax(acceptor_prob),np.argmax(donor_prob)
(349, 81)
```
So I was wondering if the warning before matters? Or anything else went wrong?

Thank you in advance!

**Comment by Ritetsu** [comment]
I tried sequence 'CGATCTGACGTGGGTGTAGGTAAGTGCATTATCGATATTGCAT' mentioned in issue #39 ，and got similar output.
So this warning seems not to be a problem.
But I am still confused about canonical splice site with very low acceptor_prob/donor_prob.
Any suggestions?

**Comment by kishorejaganathan** [comment]
The warning is benign and does not matter. There are a couple of things you can look for:
- Are you sure you're presenting the data in the correct strand?
- argmax might give you another position if it is a stronger splice site. Can you check the predicted probability at the position you are interested in?

**Comment by Ritetsu** [comment]
> The warning is benign and does not matter. There are a couple of things you can look for:
> 
> * Are you sure you're presenting the data in the correct strand?
> * argmax might give you another position if it is a stronger splice site. Can you check the predicted probability at the position you are interested in?

It's a strand problem. Thanks a lot!
