### ISSUE TITLE
Query about spliceai to calculate Delins

### ISSUE THREAD

**Issue by HXD3D0323** [Illumina/SpliceAI#146]
Hello,

I am currently using **SpliceAI in python** to analyze Delins mutation types. I noticed that when I pass a VCF file with both ref and alt fields containing more than one nucleotide, SpliceAI is unable to calculate the mutations properly. However, if either ref or alt contains only a single nucleotide, the calculation can be done successfully. Why?

But, when I use the **SpliceAI lookup website**, it is able to perform the calculation even when ref or alt contains more than one nucleotide.

Thank you for your assistance.
![微信图片_20240417141708](https://github.com/Illumina/SpliceAI/assets/149938316/00cb2708-35e3-4419-aa12-4073116ae935)
![微信图片_20240417141715](https://github.com/Illumina/SpliceAI/assets/149938316/1a553b67-0b4e-45eb-a3c9-e1491fd4006b)

**Comment by bw2** [comment]
The SpliceAI lookup website uses a [modified version](https://github.com/bw2/SpliceAI) of SpliceAI which includes added support for delins variants (see this PR  https://github.com/bw2/SpliceAI/commit/1dcd441d4e931909007f06a60c9e285c994699b0 )
