### ISSUE TITLE
whole_genome_filtered_spliceai_scores.vcf.gz of hg38

### ISSUE THREAD

**Issue by x6o6** [Illumina/SpliceAI#15]
I am interesting in using "whole_genome_filtered_spliceai_scores.vcf.gz" that is supplied as supplementary data (https://basespace.illumina.com/analyses/133298165/files/172857685?projectId=66029966). Now,  I would like to obtain this file made for hg38 genome.  Is it exist somewhere?

**Comment by kishorejaganathan** [comment]
Yes it does, we lifted over the hg19 file onto hg38. Do you have access to the files here: https://basespace.illumina.com/analyses/173156985/files/216218003?projectId=66029966

**Comment by x6o6** [comment]
Thank you for nice information.  Now I know that LiftOver is the solution to change the position of hg19 onto hg38.  Scores such as "Distance to SJ" were the same between two files.  This means that sequences of genes probably do not change between hg19 and hg38.  Is it right?

**Comment by kishorejaganathan** [comment]
The sequences change a little bit between hg19 and hg38, so liftover is an approximation. But it is a reasonable approximation, especially for the sequences within genes which don't change too much between the assemblies (the major differences are in the intergenic regions, which we do not care about for splicing).

**Comment by jeffverboon** [comment]
Can the liftover link be reshared? The above link is broken for me

**Comment by kishorejaganathan** [comment]
Try this: https://basespace.illumina.com/analyses/194103939/files?projectId=66029966

**Comment by jeffverboon** [comment]
I keep getting access forbidden

**Comment by kishorejaganathan** [comment]
Could you share a screenshot of the screen you see when you click the link? You should see something like what I have attached. You will be able to login once you create an account with BaseSpace.
![tmp](https://user-images.githubusercontent.com/20564127/67316557-85a9ba00-f4bd-11e9-9db4-a25df7e55b13.png)

**Comment by kishorejaganathan** [comment]
I'm surprised, the folders have public access and others don't have any issues accessing them. Could you try creating another BaseSpace account using a different email address and see if that works out? I tried it out with my non-Illumina email ID and it worked just fine.

**Comment by jeffverboon** [comment]
Sure

**Comment by kishorejaganathan** [comment]
Could you try this link https://basespace.illumina.com/s/5u6ThOblecrh and let me know if you can see the files (the folder genome_scores_v1.3 specifically)?

**Comment by jeffverboon** [comment]
It has something to do with being block from the broad institute ip. works
from off site, sorry for all the hassle!

**Comment by bluea9** [comment]
Hi, I'm able to access the folder genome_scores_v1.3 with the spliceai_scores.raw.indel.hg38.vcf.gz and spliceai_scores.raw.snv.hg38.vcf.gz files, but I could only find the whole_genome_filtered_spliceai_scores.vcf.gz file under SpliceAI supplementary data for hg19, where can I find the version for hg38? Thank you.

**Comment by kishorejaganathan** [comment]
The whole_genome_filtered_spliceai_scores.vcf.gz file is available only in hg19, so you will have to lift it over if you want the hg38 version. However I would just recommend using genome_scores_v1.3 scores (which is a superset of the filtered file, which only contains variants with SpliceAI score greater than a minimum threshold).
