### ISSUE TITLE
Models for 80nt, 400nt and 2K context

### ISSUE THREAD

**Issue by CDieterich** [Illumina/SpliceAI#16]
Dear Developer,

where would I find the alternative SpliceAI models presented in
the Cell Press article ?

All best wishes,

Christoph

**Comment by kishorejaganathan** [comment]
We haven't shared the sub-optimal models. I just uploaded them here: https://illumina.box.com/s/0ey4qezxeerz7kmen7w6oinqtzetcdi3 Could you let me know if you can download them? The ones with c in their names were trained using only canonical annotations, the ones with g in their names were trained using both canonical and GTEx annotations (see Methods in the paper for more details).

**Comment by CDieterich** [comment]
Hi,

I could not download the files, had to register for some business account, which is not acceptable.
Could you please put the files on some FTP site or free cloud

**Comment by kishorejaganathan** [comment]
Could you try this link: https://drive.google.com/open?id=1DrnOVmyLV2rFWWTa-lbZWzP3YzwO59K2

**Comment by flyboyleo** [comment]
Hi @kishorejaganathan ,

I wonder what do the two groups(e.g. "_c" and "_g")mean in the model files? Thank you very much.

**Comment by amir-azizi** [comment]
Dear Kishore,

I tried to use these models, but I got the following error when I directly passed them to spliceai (spliceai -I calls.vcf -O calls_spliceAI.vcf -R GRCh38.fa -A "models/SpliceNet10000_c1.h5"):

  File "/home/user/.local/lib/python3.6/site-packages/spliceai/__main__.py", line 53, in main
    ann = Annotator(args.R, args.A)
  File "/home/user/.local/lib/python3.6/site-packages/spliceai/utils.py", line 19, in __init__
    df = pd.read_csv(annotations, sep='\t', dtype={'CHROM': object})

and when I first passed them to the test_model.py routine(python3 -u test_model.py 1000 > Outputs/SpliceAI1000.txt, with correct input path "model[v] = load_model('models/SpliceNet' + str(CL)+ '_c' + str(version[v]) + '.h5')"), I get this error:

File "test_model.py", line 30, in <module>
    + '_' + '0' + '.h5', 'r')
  File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './dataset_test_0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Could you please let me know what went wrong.

-Amir

**Comment by CDieterich** [comment]
Yeah, it seems that this is hard-coded:
SpliceAI/spliceai/utils.py
Look into this.
paths = ('models/spliceai{}.h5'.format(x) for x in range(1, 6))
self.models = [load_model(resource_filename(__name__, x)) for x in paths]

**Comment by kishorejaganathan** [comment]
A few things are hard-coded into the software. These models are inferior compared to the ones used in the software (we trained them mainly to demonstrate the need for using a model with 10K nucleotide context and GTEx-based augmentation), keep that in mind while using these models. Apart from the lines pointed out by Christoph in the post above, there's another thing that needs to be changed in SpliceAI/spliceai/utils.py if you want to use these models:

(line 91) wid = 10000+cov

The 10000 here is a hard-coded parameter, which needs to be changed depending on the models you are interested in (for example, 2000 if you are using models with 2K nucleotide context).

**Comment by kishorejaganathan** [comment]
@amir-azizi Another mistake you're making: The -A flag is used to input the annotation file, not the models (see README). Use -A grch37 if you're working with hg19 assembly, or -A grch38 if you're working with hg38 assembly.
