### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by thedam** [Illumina/SpliceAI#17]
Doesn't work for me :)
```
spliceai -I test.vcf -O spliceai.vcf -R /refs/hs37d5_noHap.fa -A grch37
Using TensorFlow backend.
Illegal instruction (core dumped)

```
How to debug it?

**Comment by kishorejaganathan** [comment]
Could you just open python and try
`import tensorflow as tf`

If that doesn't work, then you have not installed Tensorflow correctly. If that works, then could you try 
`python setup.py test`
from the SpliceAI folder and let me know what happens?

**Comment by thedam** [comment]
hmm indeed the import doesn't work. There's something messed up in my conda environment...

**Comment by kishorejaganathan** [comment]
Wonderful. I'm closing this issue, feel free to reopen it if you still have issues.

**Comment by thedam** [comment]
would be perfect if you'd create a docker image :)
seems somebody tried already:
https://hub.docker.com/r/stefpiatek/spliceai

cheers

**Comment by kishorejaganathan** [comment]
Thanks for the suggestion. I wasn't sure whether the gpu version could be dockerized, will look into it.
