### ISSUE TITLE
Could you tag releases?

### ISSUE THREAD

**Issue by holtgrewe** [Illumina/SpliceAI#19]
This would make it much easier to package this, e.g., for Bioconda.

**Comment by holtgrewe** [comment]
By the way, [versioneer](https://github.com/warner/python-versioneer) is an excellent way of getting the version from the Git tag into your Python project.

**Comment by kishorejaganathan** [comment]
Thanks for the suggestion. I have added a tag for the current release, and will continue doing so moving forward.

**Comment by holtgrewe** [comment]
Would you be interested in a PR that includes versioneer? The release would then work as follows:

```
# rm -rf dist
# git tag vX.X.X
# python setup.py ...
# twine upload --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
[check that everything's fine\
# twine upload dist/*.tar.gz
```
