### ISSUE TITLE
Control number of threads

### ISSUE THREAD

**Issue by holtgrewe** [Illumina/SpliceAI#20]
Hi,

it looks like SpliceAI is using all available cores in my machine. In an HPC environment, this does not make for a good citizen :) Could you make this configuration available from the command line?

Does this help?:

https://stackoverflow.com/a/49530131/84349

Thanks

**Comment by kishorejaganathan** [comment]
SpliceAI is not supposed to use multiple cores, and others don't seem to be facing this issue. Could you let me a few more details so that I can better understand the problem?
- What OS are you running SpliceAI on?
- What version of python and tensorflow are you using?
- Do all the cores actually do useful work. In other words, does the job take less time if it is using more cores?

**Comment by holtgrewe** [comment]
Hi, I'm having a CentOS 7 machine. Running on SGE in interactive mode (I can allocate any CPU number that I want). There, I'm using the Bioconda `spliceai`  that I just created (but I expect the `pip` install to be equivalent), thus SpliceAI v1.2.1, tensorflow 1.14.0 from the conda-forge channel .

I'm running `spliceai -I .. -O ... -A ... -R grch37` and after a while I'm seeing the following in `htop`.

![image](https://user-images.githubusercontent.com/521780/62160350-08ced000-b314-11e9-9f87-efdcf491532f.png)

The output first reports output like this

```
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 16 maps to package 0 core 0 thread 1
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 2 thread 0
[...]
OMP: Info #171: KMP_AFFINITY: OS proc 13 maps to package 1 core 11 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 29 maps to package 1 core 11 thread 1
OMP: Info #171: KMP_AFFINITY: OS proc 15 maps to package 1 core 12 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 31 maps to package 1 core 12 thread 1
```

That is, only mentioning threads `0` and `1`.

And then continues like this

```OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116116 thread 1 bound to OS proc set 2
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116155 thread 2 bound to OS proc set 4
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116157 thread 4 bound to OS proc set 8
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116158 thread 5 bound to OS proc set 10
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116156 thread 3 bound to OS proc set 6
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116159 thread 6 bound to OS proc set 12
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116160 thread 7 bound to OS proc set 14
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116163 thread 10 bound to OS proc set 5
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116161 thread 8 bound to OS proc set 1
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116162 thread 9 bound to OS proc set 3
OMP: Info #250: KMP_AFFINITY: pid 116008 tid 116164 thread 11 bound to OS proc set 7
[...]
```

That is mentioning a couple of threads.

The box I'm running this on does not have a GPU.

HTH, let me know if you have any more specific questions.

**Comment by kishorejaganathan** [comment]
I managed to reproduce your observations. Could you try adding the line `export OMP_NUM_THREADS=1` (or another number that you're comfortable with) just before running SpliceAI. Alternately, you can run SpliceAI as follows: `OMP_NUM_THREADS=1 spliceai -I .. -O ... -A ... -R grch37`. That seems to solve the problem for me.

**Comment by holtgrewe** [comment]
Excellent! I'll have a look. I read somewhere about "n thousand variants per core on a CPU compared to m thousand variants on a GPU". Could you maybe quality this statement a bit further with the OpenMP finding? I would be very interested in this and IIRC I found the ~10x spread between CPU and GPU a bit disappointing :) I have a few hundred CPUs at my disposal but have to share a hand full of GPUs. I'd be stoked to learn more about such numbers and would be **greatly** interested in seeing something on the README.

**Comment by kishorejaganathan** [comment]
On a single GPU, you can score around 25K variants per hour. Our numbers for CPU was 4K variants per hour, but now I realize that the CPU benchmarks were using multiple cores (32 to be precise). I just tried limiting the CPU jobs to use only 5 cores, and the throughput dropped to 1.5K variants per hour. The job with just 1 core is still running, so I guess the numbers will further drop.

We have pre-scored all possible SNVs within genes using our GPU resources and provided the output file as part of the supplementary material. My recommendation would be to use it for SNVs and use the tool only to score INDELs (we would be providing the scores for all possible short INDELs as well in the coming weeks).

**Comment by zofieLin** [comment]
Hi, are there any methods to limit the CPU of SpliceAI? 
I am running SpliceAI (spliceai==1.3.1) with PBS on linux cluster, the command line is like below
`spliceai -I input.vcf -O output.vcf -A grch37 -R refseq `
but then the jobs always be killed by exceeded limit of CPU.

My input just contained around 1,000 variants, but it seems to require very large CPU, jobs were killed even if the CPU setting is 10 or 12.
I also tried `export OMP_NUM_THREADS=4`  in my bash script or `OMP_NUM_THREADS=4 spliceai`, but it didn't help.
Are there any solutions?

Thanks!
