### ISSUE TITLE
Caching wrapper

### ISSUE THREAD

**Issue by holtgrewe** [Illumina/SpliceAI#22]
Hi, I don't know how to best communicate it, but FWIW, I made a caching wrapper for SpliceAI.

https://github.com/bihealth/spliceai-wrapper

I'm looking forward to the announced precomputed scores for small indels. Will they be available for hg19/GRCh37 as well?

**Comment by kishorejaganathan** [comment]
The link is directing me to a non-existent page (could potentially be a permission issue). And yeah, all precomputed scores are available in both hg19/GRCh37 and hg38/GRCh38 (we score the variants in hg19/GRCh37 and then lift them over to hg38/GRCh38 as well).

**Comment by holtgrewe** [comment]
Thanks for the heads-up, I forgot to make it public.

**Comment by holtgrewe** [comment]
@kishorejaganathan also, regarding the scores. Maybe I'm overlooking something but where do I find the hg19 scores? This is what the file list looks like in Base Space:

![image](https://user-images.githubusercontent.com/521780/62237910-2b272300-b3d2-11e9-97c3-1d4bbcfda251.png)

**Comment by kishorejaganathan** [comment]
You're looking inside the genome_scores folder. Instead, look inside the supplementary data folder (we added the hg38 version later, and didn't want to change the official supplementary data folder - hence used a different folder).

**Comment by holtgrewe** [comment]
Ah, excellent.

![image](https://user-images.githubusercontent.com/521780/62238408-375fb000-b3d3-11e9-85e9-7f87d60fabfa.png)

Maybe you could add a direct link, e.g. here it would be [this one](https://basespace.illumina.com/analyses/133298165/files/172857685?projectId=66029966)?

**Comment by holtgrewe** [comment]
@kishorejaganathan Hi. Is there any news on the precomputed indels?

**Comment by kishorejaganathan** [comment]
The computations are done, only some post-processing work is left which should not take too much time. I expect it to be uploaded by the end of next week - will let you know once I upload it.

**Comment by holtgrewe** [comment]
Dear @kishorejaganathan, I have just discovered that a new version of file is available on BaseSpace. Could you shed some light on the difference between raw and masked files? Thanks,

**Comment by kishorejaganathan** [comment]
SpliceAI raw scores also include increase in the strength of canonical splice sites or decrease in the strength of non-canonical splice sites. This mode of splice-alteration is much less likely to be pathogenic than increase in the strength of non-canonical splice sites or decrease in the strength of canonical splice sites, so we created files with masked scores where we set the delta score to zero if the effect is increase in the strength of canonical splice sites or decrease in the strength of non-canonical splice sites.
