### ISSUE TITLE
Inaccurate error message when unable to write a new index file for reference fasta

### ISSUE THREAD

**Issue by tsnowlan** [Illumina/SpliceAI#24]
If the the reference genome fasta file specified is in a read-only directory, spliceai fails with:

```
ERROR:root:Reference genome fasta file /opt/reference.fa not found, exiting.
```

However, the error being thrown (with some variation in `*.fa.fai` filename) is actually:

```
OSError: /opt/reference.fa.fai may not be writable. Please use Fasta(rebuild=False), Faidx(rebuild=False) or faidx --no-rebuild.
```

We keep our references write protected to prevent accidental editing / overwriting and have already created index files for them to be used. This also causes problems if running SpliceAI in a Singularity image, as they use a read only filesystem.

**Comment by kishorejaganathan** [comment]
I've merged your changes, thank you.
