### ISSUE TITLE
Cannot access validated_preds.csv

### ISSUE THREAD

**Issue by gkaraduman** [Illumina/SpliceAI#28]
In the readme file under the supplementary data directory (https://basespace.illumina.com/analyses/133298165/files/172857685?projectId=66029966), it is mentioned that there is a file named as "validated_preds.csv" which is a list of validated splice altering variants. I cannot see such a file in the above link. Is there a way to access that?

**Comment by kishorejaganathan** [comment]
Ouch, must be an oversight from our side - will fix it after the thanksgiving break and let you know.

**Comment by kishorejaganathan** [comment]
We have added the file. Let me know if you have trouble accessing it.

**Comment by gkaraduman** [comment]
Thank you, I can reach it now.
