### ISSUE TITLE
Top-k calculations

### ISSUE THREAD

**Issue by tkzeng** [Illumina/SpliceAI#31]
I ran SpliceAI_train_code/Canonical/test_model.py (downloaded from BaseSpace) on the models provided on GitHub, and got these results: 

Acceptor:
0.9955  **0.9204**      0.9722       0.9811  0.9572      0.9878       0.6865  0.1195  0.0240  1796

Donor:
0.9967  **0.9282**      0.9833       0.9850  0.9683      0.9903       0.7042  0.1343  0.0244  1796

If I'm interpreting this correctly, the averaged top-k accuracy is between 92-92.8% (instead of ~95%). Did I maybe run this incorrectly, or was top-k accuracy calculated differently in the paper? Thanks a lot!

**Comment by kishorejaganathan** [comment]
I'm not sure I understood the "averaged top-k accuracy" phrase. Are you calculating the top-k accuracy of each of the five models one by one? If so, the 92-93% is along the lines of what we observed. You are supposed to average the output of the model (ensemble prediction) and then calculate the top-k accuracy. Let me know if that is what you are doing.

**Comment by tkzeng** [comment]
Yes, those results are from running the code (which I didn't change). I meant average across both the acceptor and donor classes. If those numbers seem right, then how is the number in the paper (95% top-k accuracy) calculated? Thanks!

**Comment by kishorejaganathan** [comment]
Where did you get the models from? If it is from the github repo, then that explains your results - those models are trained using the GTEx folder and not the Canonical folder. If you train models using the files from the Canonical folder, you should see the 95% reported in the paper.

**Comment by tkzeng** [comment]
Got it, are those models available online?

**Comment by kishorejaganathan** [comment]
Could you try this link: https://drive.google.com/file/d/1DrnOVmyLV2rFWWTa-lbZWzP3YzwO59K2/view (the models with _c*.h5 in their names) are what you are interested in.

**Comment by tkzeng** [comment]
Thanks!
