### ISSUE TITLE
Different output for same MT variant

### ISSUE THREAD

**Issue by dglemos** [Illumina/SpliceAI#32]
Hello, I'm running SpliceAI to annotate all possible ref/alt alterations in chromosome MT (within genes). I run the same job twice, once with 32 cores and a second time with 2 cores - it was used the same input file, same default values and same fasta file. 
I would expect to get the same output however, there's one variant with different DP_AL. 

Output run with 32 cores: 
`MT    5173    .       A       T       .       .       SpliceAI=T|MT-ND2|0.00|0.00|0.00|0.00|10|-32|9|3`
Output run with 2 cores: 
`MT    5173    .       A       T       .       .       SpliceAI=T|MT-ND2|0.00|0.00|0.00|0.00|10|3|9|3`

Was this behavior observed before? 
Thanks in advance.

**Comment by kishorejaganathan** [comment]
Hi Diana,
This difference is numerical precision-related. You will only see this for delta positions corresponding to delta score = 0. In particular, there is an argmax operation trying to decide which position has the highest splicing change between ref and alt, which in this case ends up being an argmax over a vector consisting of a lot of values extremely close to 0. Only delta scores > 0.1 are considered interesting, and you will not run into this issue for those variants.

Regards,
Kishore
