### ISSUE TITLE
The basespace link seems to be no longer active

### ISSUE THREAD

**Issue by rybval** [Illumina/SpliceAI#42]
This address is mentioned in the [README.md](https://github.com/Illumina/SpliceAI/blob/master/README.md) and in the paper.
https://basespace.illumina.com/s/5u6ThOblecrh

Unfortunately, I am getting the following error when trying to access the aforementioned URL:

> Invalid Invite
> We're sorry, but the current invitation is invalid or no longer active.

**Comment by kishorejaganathan** [comment]
Looks like the link expired, could you try this one and let me know if it works: https://basespace.illumina.com/s/l74ChDRXkhBd

**Comment by rybval** [comment]
It worked, thank you, @kishorejaganathan !

**Comment by kishorejaganathan** [comment]
The data has been moved to a permanent link: https://basespace.illumina.com/s/otSPW8hnhaZR
