### ISSUE TITLE
SpliceAI - Annotations for all possible substitutions link not working

### ISSUE THREAD

**Issue by esalfati** [Illumina/SpliceAI#44]
Hi,

Where could we retrieve the data posted on this link:
https://basespace.illumina.com/s/5u6ThOblecrh 

Best,

Elias

**Comment by esalfati** [comment]
Updated link:
https://basespace.illumina.com/s/l74ChDRXkhBd

**Comment by kishorejaganathan** [comment]
The data has been moved to a permanent link: https://basespace.illumina.com/s/otSPW8hnhaZR
