### ISSUE TITLE
Gene AC068620.1 location

### ISSUE THREAD

**Issue by dglemos** [Illumina/SpliceAI#45]
I was checking the SpliceAI scores for variants in the gene `PPAT` from file: `spliceai_scores.masked.snv.hg38.vcf.gz` and I noticed this gene overlaps gene `AC068620.1`.  
Example: 
```
4       56410516        .       A       C       .       .       SpliceAI=C|AC068620.1|0.00|0.00|0.00|0.00|6|8|38|-22
4       56410516        .       A       C       .       .       SpliceAI=C|PPAT|0.01|0.00|0.00|0.00|-1|27|0|-41
4       56410516        .       A       G       .       .       SpliceAI=G|AC068620.1|0.00|0.00|0.00|0.00|1|6|-1|38
4       56410516        .       A       G       .       .       SpliceAI=G|PPAT|0.00|0.00|0.00|0.00|27|-37|-41|0
4       56410516        .       A       T       .       .       SpliceAI=T|AC068620.1|0.00|0.00|0.00|0.00|6|0|50|-22
4       56410516        .       A       T       .       .       SpliceAI=T|PPAT|0.00|0.00|0.00|0.00|27|-37|-41|-42
```
From the scores file we can see that `AC068620.1` has coordinates `4:56410516-56410965`. However, in GRCh38 this gene has coordinates `4:56387625-56388153` (which doesn't overlap `PPAT`). 
Is there any explanation of why this is happening?

**Comment by kishorejaganathan** [comment]
We only scored the variants in GRCh37, the GRCh38 files were obtained via liftover of the results in GRCh37. The coordinates for AC068620.1 and PPAT overlap in GRCh37, which is why this is happening.

**Comment by kishorejaganathan** [comment]
More generally, for GRCh38, you can ignore all the genes which are not present in this file spliceai/annotations/grch38.txt . This would be the simplest way by which you will not face any such issues. A few hundred genes are not present in this file for a variety of reasons:
- We weren't able to find a perfect match between the canonical transcript in GRCh37 and some transcript in GRCh38. If you can indeed find a match for more genes, then you can consider the scores for variants in those genes. 
- Liftover issues (for example: https://github.com/Illumina/SpliceAI/issues/34)

I'm closing this issue, but do feel free to reopen or reach out to me if you have further questions.

**Comment by dglemos** [comment]
Thanks for the clarification, now it makes sense what's happening.
