### ISSUE TITLE
GRCh38 Concatenation Issue

### ISSUE THREAD

**Issue by persadg** [Illumina/SpliceAI#47]
When I tried to run SpliceAI on a list of variants on hg38 I obtained this error message. Looks to be something with numpy concatenate that is used within SpliceAI. 

![image](https://user-images.githubusercontent.com/66142531/83306221-2be63c80-a1d0-11ea-9ea3-d66b39fe3ec4.png)

Any help would be much appreciated!

**Comment by kishorejaganathan** [comment]
Could you let me know what the variant is? This shouldn't happen with the latest version of SpliceAI...
