### ISSUE TITLE
SpliceAI prediction for 2.8kb deletion

### ISSUE THREAD

**Issue by leekaiinthesky** [Illumina/SpliceAI#51]
Hello,

Thank you so much for providing this software.

I am trying to run splicing prediction on the below intronic deletion. When I put it in my input VCF and run `spliceai -I in.vcf -O out.vcf -R hs37d5.fa -A grch37`, my output VCF shows SpliceAI output for the other variants in my VCF but not for this long deletion.

I went back to the FAQ and realized I should expect this behavior, since the deletion is greater than twice the input parameter `-D`. So I reran with `spliceai -I in.vcf -O out.vcf -R hs37d5.fa -A grch37 -D 4999`, and there is still no output provided for this variant.

Can you help me figure out why?

I do get the below warnings, but they have not impeded me in the past:
```
2020-07-09 12:03:01.876276: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-09 12:03:01.899785: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fefd3896dc0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-09 12:03:01.899804: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/usr/local/lib/python3.7/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
```

And here is the variant I am trying to run prediction on:
```5	142047933	.	GTGGTCGCTAAAGCTCCCGCATTCGTGATGTTTATGTGACCGTGACTTGTCACATGACCTTGGGGAGGCTGCTCTTGTCTTCACTGTCCCATCCTCTTGACACCCCTCCCTGCCCCGGCCCCAGTAAGGACTTATATACAAGGAACTCACCCAGACACAGTTAGGTAATAAAGGTGAAGTCATGGTCAAGGGCATGGGTTTTGAAGTGAAGCTTCCTGAACTTAAGTCCAGAAAGTCAATTCATCTCTCTGAGCTTCCTTTATAAAAGGAGGCCAGTGATATACCTACCTCACGTGTTTGTCAAAAGGTTGCAACAAGATAGTGCAAGGGAAGCACCTAGCACATTGCCTCATATAAATAAAATATGCATTCTAACATCTCATAATTTTAGCTATTATTTTTGTTGTGATTATTCAGGATGAATGAGATAAGCTTCCTGTCCTTGAAAGAAGGTGAGAAGCTAAGTCATAAATACCATGACAAGCTATGATAAGTGCTGTGAAGGTTGTGCCAAGGGCTGGGGGGATGGATGGAGGGCTGAAGAGGAAGGGGTCAGGAGGACTTTCTGGAAGATGTGGCATCTCAGCAGGAAGGACAAACAGGTTTTACATATGTGGGCATGGAATAAAGGAATCACTTGAACAGAGGCCCAGGGGTGGGCAAGTAGAGGGCATCTTCGCCCAGCATGCATGGCTGATGCCGCTGAGCGGGGGGTTTTCAGGGACACACAGGGTTAGTGCAAGCTAGCTTGGAGTCAGATCATAGAGGACCTTGAATGATGCTGTTCCAAAGCATTTAGACTTTTTTCTGCAAGCAAATGAAAGTGGAGCCAGTGGAGACTTTGGAGAAGGGAATTTGGAAATTCTTCTGGAAAATTGTTGGTTACTGGTAGGGGGCTGGGCAGAGCAGAGGCCACGGGGCACAGTATCCTCTATTTCCATCTCTGAAAAGCTCATCAGCCCTCAAGTCTTCTTGACTAGACTACAAGCCAGTCGAGGACAGAAGCATGAGCTTCCTTCTCACGATTATGTCCCCAGCACAGCCCCTGGGGCTCAATAAATGGCTGTTGAATTGAAATAGACAAAAGATCCTAAACTTGAGCCATGAGAGTGGAAGGGAGAGATGGCTCCAAAGACACTCCAGGAGAAGAATGAAGAGGATTCTGCAAAGGAGTAATCAGAGGTGACTCGGGCATAGAGGGACCGGAAGGATGAATGGAGAGGCTATTTACTGAGAGAATGGACGCAGCCAGGAGCAGCCCATCTGGCAGGACGACTGCTGCACTCGCTGTGGGGCGTGTCGCGGCTGAGGTGAACAGAGTCATCCATCTGCTGACTGGCAGGCAGTGGACGCGAGCTCTGGAGAGAACCCAGAATATGAGGCAGGCACAGGAGAAGCAGAGCAGAGGGGAAAGATGAGATCTGCAAGGAAGAACAGCCTGGAGCCTGAAGAGCGAAGCAGACAGCGGCAGCCACCCTGGGGGTCACTCCACACTCTGAGATCCCCAGTGCAGCCGGTTACCACAGAGGAGCAACCCCAGGATCCTGGGGAGAAGAGGCACAGTCAGGAGGAGAGCCAAGAAGTACAGGATCACAGCCTTCAAGGGAGAAGTCAGCTGGTCTGCACTGCCCGAAGCTACAAAGAGGTTAACCAGAGTGGAAAGTGGGTGCCGGAGCCTCGGGATTGATCTCCTGCCCCACAGCTTTGCTGTTCCCGTCACTTCTGCACACTGGCACTGAGGTCATGCTTCTCAAGAAAGATCTGCATGTGCCAACCATTGGCTCAGAAACCTTCCCTTGTTTCCTACTTCCCAGCTAGGAAGGCCAAAGTCCTTGGCCAAGTGACCTCAAATCTGGTGTGAAAAGCCTCACCTTCCACTACGTCCTTCCACATCCCAGCAATCTGAGCTGCTCCCTCTCCCCTGTTGCACACCAAGAACTTCCATGCCTTCCTATGTTGGTTCTTGCTGTTCCCTCAGCTAGGAAGGCCATTTTGCTCAATGTTCTGCTAATTAAAACTCTCCTCATCCTTCAAGGCCTATGTCAAATGCTACCTCCACTGCAAAGCCTTCCTTGGTCTCTCCAGTCAGTAGGGTCCTTCCTTCAAGGACCCACGGTGTGGTGCTTTGCCTAGTCATTACTTCATTCTTTCTACAATTGAGTTGTTGGCCCCCATCCACTCACACATGACAGCATGAGAGCAGAGAACATGTTTTATCTTTGAATCTCCCATGGTATAGATTCTTACATGCAGAAGGCACTCAACCAACGCCAGCAAAGCATATGAAGAAATTAGGAAAAAAACCCCACAAAAACCTGACAGCAGTAGATGCTACCACTTCCAATCATTTATTTGGAAATTACGATGTGCCTCACAGTTATTTGGACTTCAGGGGTTTTGCCCTGCAATTAATGTCTCGGCCCGATGTTGGGTTGCCTTACAATCACATGTGTTATCTGTGATCTCTAGGGCCATTTCGGTTTTGAGAGCACACTATTGCACATACACTAAGATGTTTCTGAGTATTTCCCATAGTTAGACAAAAATGGAAAAACTTGGCCCAGCCTTCAGAAGCGCTTTATCACATGTGCTGCCTATGACAGTGGTTTAGGGAAATCTCTACACAATTCCACCAGGATCATAAACACATTTCCTGAGCTATGAATTAAGAGGAAAAAGTTTCTCAACATGCAACACAAACTCAAAAAGCAGCTGTTCATTTAACCATCTATCATCTTCTTTTGACCCTTTGAACAGGCTCTGACAGTATTTAGATTACATGAA	G```

Thanks very much for your time and help,
Lee-kai

**Comment by kishorejaganathan** [comment]
As mentioned in FAQ #1, SpliceAI only annotates variants which are deletions of length less than twice the input parameter D (defaulted to 50). If you rerun SpliceAI with -D 1500, you should be able to get the annotation for this variant as well.

**Comment by kishorejaganathan** [comment]
I just realized that you've already tried this, sorry - my bad. Could you let me know what SpliceAI does to that variant? In particular, do you not see any annotation at all or do you see SpliceAI=.|.|.|...?

**Comment by leekaiinthesky** [comment]
No annotation at all for that variant. Thanks. :)

**Comment by kishorejaganathan** [comment]
The reason turns out to be another point mentioned in FAQ #1: The variant belongs to FGF1 gene but the canonical transcript we use for that gene starts and ends at 141971742	and 142000907 respectively (the variant is outside these limits), so if you need the annotation for this variant then you have to use a different (longer) transcript for FGF1.

**Comment by leekaiinthesky** [comment]
@kishorejaganathan Thanks for spending the time to look into it.
