### ISSUE TITLE
How can I compute SpliceAI scores for non-coding variants?

### ISSUE THREAD

**Issue by bw2** [Illumina/SpliceAI#52]
Hi, I'd like to run the spliceai tool to compute the SpliceAI scores for any non-coding variant.
What is the right way to do this to match the scores in the precomputed tables?

**Comment by kishorejaganathan** [comment]
The default settings were used to generate the precomputed tables. Here are a few pointers that can help:
- Reference genome (hg19/hg38): We have provided the download link in the README.
- Annotation file: If you are interested in regions/genes that are outside what we have used, then I would recommend expanding the annotation files in spliceai/annotations (i.e., adding new lines corresponding to extra genes/transcripts).

**Comment by bw2** [comment]
Sorry for the basic question. That makes sense, and I have it working now. Thanks.
