### ISSUE TITLE
version info of dependencies

### ISSUE THREAD

**Issue by XiaoleiZ** [Illumina/SpliceAI#53]
Hi, 

What's the exact version of python, Tensorflow and other dependencies compatible with spliceAI? Could you show update the compatible version info or ideally provide a docker container? I tried to install using the latest version by default but came across errors when calling spliceAI. Thanks.

**Comment by kishorejaganathan** [comment]
Hi Xiaolei,
Could you copy/paste the errors so that I can better guide you? SpliceAI was originally tested on Keras 2.0.5-2.2.4 and Tensorflow 1.2-1.9. Recently, I tested it out with Keras 2.3 and Tensorflow 2.0, and that worked fine as well. Some versions of Keras are not compatible with some versions of Tensorflow, and my guess is that's what is causing the errors for you. What version of Keras and Tensorflow are you using?

Regards,
Kishore

**Comment by XiaoleiZ** [comment]
Thanks. The problem is solved now by installing again (don't know what happened before). It works well with the Tensorflow 2. 

The packages I am using:
absl-py==0.8.0
aiohttp==3.6.2
asn1crypto==0.22.0
astor==0.8.0
astunparse==1.6.3
async-timeout==3.0.1
attrs==19.3.0
backcall==0.2.0
bleach==1.5.0
bokeh==1.2.0
cachetools==4.1.1
certifi==2020.6.20
cffi==1.10.0
chardet==3.0.4
conda==4.5.13
cryptography==1.8.1
Cython==0.29.20
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
gast==0.3.3
gnomad==0.3.0
google-auth==1.19.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.12.1
h5py==2.10.0
hdbscan==0.8.26
html5lib==0.9999999
humanize==1.0.0
idna==2.6
idna-ssl==1.1.0
importlib-metadata==1.7.0
ipykernel==5.3.0
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.1
Jinja2==2.11.2
joblib==0.15.1
jsonschema==3.2.0
jupyter-client==6.1.5
jupyter-core==4.6.3
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
mistune==0.8.4
mkl-fft==1.0.4
mkl-random==1.0.1
mock==3.0.5
multidict==4.7.6
nbconvert==5.6.1
nbformat==5.0.7
notebook==6.0.3
numpy==1.18.0
oauthlib==3.1.0
opt-einsum==3.2.1
packaging==16.8
pandas==0.23.4
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
prometheus-client==0.8.0
prompt-toolkit==3.0.5
protobuf==3.12.2
ptyprocess==0.6.0
pyasn1==0.2.3
pyasn1-modules==0.2.8
pycosat==0.6.3
pycparser==2.18
pyfaidx==0.5.5.2
Pygments==2.6.1
pyOpenSSL==17.0.0
pyparsing==2.2.0
pyrsistent==0.16.0
pysam==0.11.2.2
python-dateutil==2.8.0
pytz==2019.3
PyYAML==3.12
pyzmq==19.0.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-learn==0.23.1
scipy==1.4.1
Send2Trash==1.5.0
six==1.15.0
slackclient==2.5.0
spliceai==1.2.1
TBB==0.1
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow==2.2.0
tensorflow-estimator==2.2.0
tensorflow-tensorboard==1.5.1
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
threadpoolctl==2.1.0
tornado==6.0.4
traitlets==4.3.3
typing-extensions==3.7.4.2
urllib3==1.25.9
wcwidth==0.2.5
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.12.1
yarl==1.4.2
zipp==3.1.0
