### ISSUE TITLE
Refactor get_delta_scores(..) to allow access to raw absolute scores.

### ISSUE THREAD

**Issue by bw2** [Illumina/SpliceAI#55]
To allow for different ways of displaying model predictions, it would be nice to move 
https://github.com/Illumina/SpliceAI/blob/master/spliceai/utils.py#L96-L176
to a separate function (something like `get_raw_scores(..)` or `run_model(..)`?) which would return y_ref, y_alt, dist_ann[2], genes. Then, external code (and `get_delta_scores(..)`) could call this function to get both masked and raw delta scores in one go, and also could allow different visualizations of y_ref and y_alt. 
If you agree with this idea, would you be open to a PR?

**Comment by kishorejaganathan** [comment]
I agree with the idea/thought process of being able to visualize in different ways, but am not convinced about the benefits of moving those lines into a separate function. As in, it takes the same amount of effort to edit what follows L176 regardless of whether the lines preceding it are in the same function or a different one right?

**Comment by bw2** [comment]
I'm not sure I follow. It would be nice to be able to call some function(s) to get `y_ref`, `y_alt`, `dist_ann[2]`, but I'm 
 assuming the `get_delta_scores(..)` interface needs to stay the same for backward compatibility,
