### ISSUE TITLE
Performance Warnings with Tensorflow 2.3.0

### ISSUE THREAD

**Issue by segoerge** [Illumina/SpliceAI#56]
Hi,
I'm getting a few of the following warnings after updating Tensorflow to version 2.3.0:

```WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fbdf4728d08> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details. ```

Can this be ignored or should I better downgrade to version 2.2.0 ?

Thanks and best regards,

Sebastian

**Comment by kishorejaganathan** [comment]
Seems like it can be ignored. Just to be sure, could you try to run SpliceAI with spliceai/examples/input.vcf file as input and verify that the output matches spliceai/examples/output.vcf ?

**Comment by segoerge** [comment]
Yes, I tried and the output matches!

**Comment by kishorejaganathan** [comment]
You can ignore the warnings then...
