### ISSUE TITLE
PyVCF.reader crashes on SpliceAI generated VCF

### ISSUE THREAD

**Issue by dmcgoldrick** [Illumina/SpliceAI#57]
Hi SpliceAI masters --

Has anyone noticed that when reading in a SpliceAI vcf file when computed de novo that the python PyVCF parser .reader class crashes on 

"##ALT=ALT from Sutr file"

Is this a duplicate definition that breaks the VCF spec? I took it out and all is better...

Thanks for the excellent work!

Daniel

**Comment by kishorejaganathan** [comment]
Could you please post an example VCF so that we can reproduce the error? Just the header and a couple of variants should be enough...
