### ISSUE TITLE
Bug in precomputed hg38 SpliceAI scores

### ISSUE THREAD

**Issue by aryakaul** [Illumina/SpliceAI#58]
OR4F5 gene is located at position chr1:69091-70008 in hg19 and at position chr1:69055-70108 in hg38.

In both raw and masked precomputed vcfs for hg38, OR4F5 is computed on the hg19 coordinates. I manually checked a couple random genes and they all look fine, so I think it is just an off by 1 error

**Comment by kishorejaganathan** [comment]
The gene annotation file we downloaded from genome browser for hg38 (GENCODE v24) has the following coordinates for OR4F5: chr1:69090-70008 (same for hg19 version as well). We did the SpliceAI calculations only for hg19, and obtained the hg38 files via liftover.

**Comment by aryakaul** [comment]
Ah I see, I'm going off GENCODE v32 annotations. I'll lift the VCFs over to the later version then. Thanks!
