### ISSUE TITLE
Consider not INFO field for non-predictions?

### ISSUE THREAD

**Issue by CarlosBorroto** [Illumina/SpliceAI#6]
Would it be better to not output an INFO field for non-predictions? VCF specs allow for this. It would make the output smaller and easier to grep for variants with predictions. I'm getting a lot of `SpliceAI=[ACGT]+|.|.|.|.|.|.|.|.|.`.

Thanks for the tool. It was dearly needed.

**Comment by kishorejaganathan** [comment]
Thank you for the suggestion, we have incorporated it into the current version (v1.2).
