### ISSUE TITLE
Access to training code?

### ISSUE THREAD

**Issue by rsmichael** [Illumina/SpliceAI#60]
Hi,

Your Cell paper indicates that the code to train your model is available at the following address:

https://basespace.illumina.com/s/5u6ThOblecrh

When I log into BaseSpace and then try this link, I get the following error:

"We're sorry, but the current invitation is invalid or no longer active."

Can you indicate how to access the code and relevant annotations for training?

Thank you!

**Comment by kishorejaganathan** [comment]
Unfortunately, that link expired. All the supplementary material, including the training code, is now available here: https://basespace.illumina.com/s/otSPW8hnhaZR

**Comment by rsmichael** [comment]
Thank you for your prompt response!!
