### ISSUE TITLE
Filtered "spliceai_scores.raw.snv.hg38.vcf.gz" file

### ISSUE THREAD

**Issue by jcorominas** [Illumina/SpliceAI#63]
I am interesting in using the filtered version (DS >0.1) from the file "spliceai_scores.raw.snv.hg38.vcf.gz" that can be downloaded from basespace. This is provided for hg19, but this file exist for GRCh38?

**Comment by kishorejaganathan** [comment]
No, unfortunately it does not exist for GRCh38. You will have to download the full file and filter it yourself (a simple grep command should do the job).

**Comment by jcorominas** [comment]
Thanks, I did that.
