### ISSUE TITLE
Are models trained on all chromosomes?

### ISSUE THREAD

**Issue by tkzeng** [Illumina/SpliceAI#64]
Are the models in this repository trained on all chromosomes, or on the training chromosomes described in the paper? What about these models? https://drive.google.com/file/d/1DrnOVmyLV2rFWWTa-lbZWzP3YzwO59K2/view

If they have all been trained on all chromosomes, do you have the models that were trained on just the training chromosomes? 

Thanks a lot!

**Comment by kishorejaganathan** [comment]
All models (both in the repo and google drive) are only trained on the training chromosomes described in the paper. We do not have any models that were trained on all chromosomes.
