### ISSUE TITLE
One-Based Vs Zero-Based Coordinate Systems

### ISSUE THREAD

**Issue by CarlosBorroto** [Illumina/SpliceAI#66]
We are running SpliceAI using genome annotations from [RefSeq GFF](ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh37_latest/refseq_identifiers/GRCh37_latest_genomic.gff.gz
) file. This GFF file uses one-based coordinate system. When comparing with the annotation file provided by SpliceAI, we see a consistent off-by-one for the start positions. This makes us think the SpliceAI file is zero-based. We also see SpliceAI is using `pysam.VariantRecord.pos` value for the variant position input which is a one-based coordinate.

Can this mismatch between the annotation and input coordinates used by SpliceAI cause problems? I'm assuming the model was trained with the mismatch. Should we adjust the RefSeq GFF annotations to be 0-based before using it with SpliceAI?

**Comment by kishorejaganathan** [comment]
SpliceAI uses 1-based system as well. It assigns high acceptor and donor scores to the first and last bases of an exon, maybe that's the reason behind the mismatch?

**Comment by CarlosBorroto** [comment]
That could explain it. Although, the end result would be the same as switching the coordinate system. Am I reading correctly that it would be very important to match how annotations are defined? Otherwise, we would be tricking SpliceAI to incorrectly assign the first base of an exon?

**Comment by kishorejaganathan** [comment]
It is best to follow the same protocols followed during training SpliceAI:
- 1-based coordinate system
- Assign high values during predictions for first and last positions of an exon

For annotations, note that the files downloaded from UCSC genome browser contains the positions corresponding to last base in exon and last base in intron. https://github.com/Illumina/SpliceAI/blob/76ef672108c429cac1f49226ef87bdf8d9932482/spliceai/utils.py#L25 
has a +1 operation to move the last base of intron to the first base of the exon. Changing base from 1 to 0 won't fix the problem I think, as the +1 operation is done only for exon_starts and not exon_ends.

**Comment by CarlosBorroto** [comment]
Thanks for you response, I think we now understand what we need to do to get our annotations to match what SpliceAI is expecting.

BTW, the way I understand coordinate systems, as explained by this [post](https://www.biostars.org/p/84686/), is that only starts are shifted between `0-based` and `1-based`. I think this image from the linked post explains it best.

![single_nucleotide_or_variant](https://user-images.githubusercontent.com/240588/102255689-65666700-3ed8-11eb-987b-6d3f4b714a8f.jpg)
