### ISSUE TITLE
Running custom sequence doesn't produce an output

### ISSUE THREAD

**Issue by arton2008** [Illumina/SpliceAI#67]
I'm trying to run custom sequence script for a sequence that is about 20Kb long. The script seems to be running to the end without any error except few warnings. However, I am not getting any output file which is strange because the sequence I am submitting has atleast two splice sites. I copied the script I am running below (the sequence is replaced with few Ns because it is too large to copy here):
I would appreciate your help.

```
from keras.models import load_model
from pkg_resources import resource_filename
from spliceai.utils import one_hot_encode
import numpy as np

input_sequence = 'NNNNNNNN'
# Replace this with your custom sequence

context = 10000
paths = ('models/spliceai{}.h5'.format(x) for x in range(1, 6))

models = [load_model(resource_filename('spliceai', x)) for x in paths]
x = one_hot_encode('N'*(context//2) + input_sequence + 'N'*(context//2))[None, :]
y = np.mean([models[m].predict(x) for m in range(5)], axis=0)

acceptor_prob = y[0, :, 1]
donor_prob = y[0, :, 2]
```

**Comment by kishorejaganathan** [comment]
The results for acceptor and donor will be stored in the variables acceptor_prob and donor_prob respectively. If you are running the script in an interactive environment, you can use these variables for downstream processing/plotting. If it is not an interactive environment, you can print the values for these variables into a file and then use that file for downstream processing/plotting.

**Comment by arton2008** [comment]
Thank you for the quick response. 
Right. The output is in the variables. It's tricky for users who don't know Python. I printed the output into a file. The output was a line of scores but how can we know where these scores belong to in the 20Kb long sequence?

**Comment by kishorejaganathan** [comment]
The number of lines in the output file will be equal to the length of the input sequence. The i'th line in the output file will correspond to the i'th position in the input sequence.

**Comment by arton2008** [comment]
Oh. I see. I must be printing only the last line. Thank you.
