### ISSUE TITLE
Getting SpliceAI annotations per bp in an input sequence (where output would be probability over donor/acceptor/neither)

### ISSUE THREAD

**Issue by joycekang** [Illumina/SpliceAI#69]
Hi! Thanks for the awesome work. Currently, the input is a vcf file, where output is how variants are likely to affect splicing (deltaScores). I was wondering if there's a way to input a pre-mRNA sequence and the output would be the per-bp scores of how likely it is for each position to be a donor/acceptor/or neither, similar to Fig. 1B in your paper, rather than the deltaScores for a given vairant. Is this possible? Thanks!

**Comment by kishorejaganathan** [comment]
Yes, please see FAQ #3 in the github readme page.

**Comment by joycekang** [comment]
Thanks so much! I was wondering if you had any advice for how to handle sequences for genes located on the reverse strand. I tried to predict the SpliceAI scores per base pair for the HBB gene, which is on the '-' strand, and got a wonky result presumably because I inputed the reverse complement. For reference, the result for the HBA1 gene (on the '+' strand) looks great: 
![image](https://user-images.githubusercontent.com/12923683/106991271-e22cf900-6743-11eb-8681-42d823dafd83.png)

**Comment by kishorejaganathan** [comment]
Giving the reverse complement sequence as input is the correct approach (SpliceAI takes as input RNA sequence). Could you try a few more examples on the negative strand?

**Comment by joycekang** [comment]
Found the bug! I was taking the reverse complement, but the function I used to pull the sequence from the "-" strand already handles the reverse complement it seems, so I was doing it twice which obviously defeats the purpose. Thanks for the prompt response!
