### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gopi1616** [Illumina/SpliceAI#72]
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
Traceback (most recent call last):
  File "spliceai/1.3.1/Python-3.6.7/bin/spliceai", line 11, in <module>
    sys.exit(main())
  File "spliceai/1.3.1/Python-3.6.7/lib/python3.6/site-packages/spliceai/__main__.py", line 72, in main
    scores = get_delta_scores(record, ann, args.D, args.M)
  File "spliceai/1.3.1/Python-3.6.7/lib/python3.6/site-packages/spliceai/utils.py", line 111, in get_delta_scores
    chrom = normalise_chrom(record.chrom, list(ann.ref_fasta.keys())[0])
IndexError: list index out of range

**Comment by kishorejaganathan** [comment]
The warnings are benign and can be ignored. Could you please let me know the full command you used to call SpliceAI? Additionally, a couple of lines in the input VCF will help me debug.
