### ISSUE TITLE
Different results between SpliceAI 1.3.1 on cluster versus Broad web version

### ISSUE THREAD

**Issue by cpsosa** [Illumina/SpliceAI#75]
Hi,

I am running a version of SpliceAI 1.3.1 installed on our cluster and comparing the results to my run using the BROAD web version.  The first two rows of the table below show perfect match.  However, the last two rows on the cluster DP_AL is 25 and DP_DG is 26.  The web version does not provide any value.  

Do you know why there is a difference in selected cases?  The issue for all the variants that I have tested seem to appear only for the pre-mRNA position.

I am using all defaults in both cases including hg19.

Thanks

             | Variant | ALLELE | SYMBOL | DS_AG | DS_AL | DS_DG | DS_DL | DP_AG | DP_AL | DP_DG | DP_DL
Cluster | 1-94488942-C-T | T | ABCA4 | 0 | 0.71 | 0 | 0.55 | 0 | 32 | 32 | 0
Web     | 1-94488942-C-T | T | ABCA4 | 0 | 0.71 | 0 | 0.55 |  | 32 |  | 0
Cluster | 1-94470997-C-T | T | ABCA4 | 0 | 0 | 0 | 0.97 | 0 | 25 | 26 | 0
Web     | 1-94470997-C-T | T | ABCA4 | 0 | 0 | 0 | 0.97 |  |  |  | 0

Please let me know if you need additional information.

**Comment by kishorejaganathan** [comment]
Hi Carlos,
The web version was developed by Broad independent of us, could you please reach out to the creators themselves in order to figure out what is going on?

Regards,
Kishore

**Comment by cpsosa** [comment]
Thank you.  I just opened the same issue at the Broad.  I'll update this issue.

**Comment by cpsosa** [comment]
Hi Kishore,

Solution.  The web version does NOT display the mRNA position when the
delta score is 0.  Hence, I saw the difference.  They are using SliceAI
1.3.1.

Thanks
