### ISSUE TITLE
Coverting probability to delta score

### ISSUE THREAD

**Issue by wososa** [Illumina/SpliceAI#76]
Dear developers,

Thanks for developing this interesting tool. I get probability numbers from your custom sequence example:

`
array([3.4042550e-06, 2.7170695e-06, 5.1883144e-06, 7.5550730e-07,
       2.1583460e-06, 1.5086046e-06, 2.0202424e-06, 5.0430872e-06,
       2.6342183e-05, 4.7420731e-06, 5.6451463e-06, 1.7478824e-06,
       6.8690401e-06, 4.5418251e-06, 7.0418655e-06, 1.2982507e-06,
       1.4428298e-06, 2.9488924e-06, 1.1093880e-05, 2.2232302e-06,
       5.4766997e-06, 5.9818544e-06, 6.5312915e-06, 3.1644518e-06,
       2.5100337e-06, 7.8444300e-06, 1.6804267e-06, 1.4056599e-06,
       4.9439204e-06, 1.5622132e-05, 1.4604024e-05, 1.2897204e-06,
       4.2190541e-06, 2.4796402e-06, 1.1721451e-05, 3.2490138e-06,
       7.9263891e-06, 2.3166267e-06, 1.6690603e-06], dtype=float32)
`

How do I convert this to the delta score so that I can compare the output from custom sequence with the output from regular spliceai?

Thanks,
Woody

**Comment by kishorejaganathan** [comment]
You have to run this script once with the regular sequence and once with the custom sequence (of same length). Then, the operation np.mean(array_reg - array_custom) will give you the delta score.

**Comment by wososa** [comment]
Hi @kishorejaganathan ,

Thanks for quick reply. I did something like this:

`input_sequence = 'CGATCTGACGTGGGTGTCATCGCATTATCGATATTGCAT'`
`ref = 'CGATCTGACGTGGGTGTCATCGCATTAGGGTATTGCATA'`
`x1 = one_hot_encode('N'*(context//2) + input_sequence + 'N'*(context//2))[None, :]`
`x2 = one_hot_encode('N'*(context//2) + ref + 'N'*(context//2))[None, :]`
`delta = np.mean([models[m].predict(x1) for m in range(5)]-[models[m].predict(x2) for m in range(5)],axis=0)`

And I got error like this:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for -: 'list' and 'list'`

x1 is input sequence and x2 is from ref sequence. Could you tell me how to do this correctly?

Thanks,
Woody

**Comment by kishorejaganathan** [comment]
You can't subtract lists, you have to convert them into an array via np.asarray([]). Here is the operation, let me know if that works:

np.mean([models[m].predict(x2) for m in range(5)], axis=0) - np.mean([models[m].predict(x1) for m in range(5)], axis=0)

**Comment by wososa** [comment]
Yes, it seems to work.

I did:
`delta = np.mean([models[m].predict(x2) for m in range(5)], axis=0) - np.mean([models[m].predict(x1) for m in range(5)], axis=0)`
I got:
`delta
array([[[-6.55651093e-07,  7.13335794e-07, -1.20903962e-08],
        [ 4.76837158e-07, -2.01326657e-07, -3.17519493e-07],
        [ 1.72853470e-06, -1.54724648e-06, -1.63646448e-07],
        [ 7.74860382e-07, -5.14974431e-07, -2.73038296e-07],
        [ 3.57627869e-07, -3.59005639e-07, -1.38790980e-07],
        [ 1.25169754e-06, -3.48116828e-07, -8.78436424e-07],
        [ 1.49011612e-06, -8.03806415e-07, -8.36989670e-07],
        [ 1.31130219e-06, -1.18018534e-06, -1.15686269e-07],
        [ 8.62419605e-04, -1.52046568e-05, -8.47171410e-04],
        [ 7.74860382e-07, -7.89219030e-07, -5.83368092e-08],
        [ 1.60932541e-06, -2.69682459e-07, -1.35989512e-06],
        [ 1.90734863e-06, -2.69160296e-07, -1.68335396e-06],
        [-1.72853470e-06,  1.25159886e-06,  4.40857548e-07],
        [-4.76837158e-06,  4.92934396e-06, -1.24186471e-07],
        [ 9.17911530e-06, -1.56149690e-06, -7.64671677e-06],
        [ 1.13248825e-06, -7.11850930e-07, -4.73231069e-07],
        [-2.92062759e-06,  2.71545150e-06,  1.61568494e-07],
        [-1.49011612e-06,  1.89151706e-06, -3.28273785e-07],
        [ 6.67572021e-06, -5.56776331e-06, -1.06088214e-06],
        [-1.07288361e-06,  1.16260026e-06, -1.31522157e-07],
        [-1.81198120e-05,  1.82455587e-05, -5.11809333e-08],
        [-9.53674316e-07,  1.27647945e-06, -3.69683022e-07],
        [-7.92741776e-06,  7.57797307e-06,  3.51060066e-07],
        [-5.36441803e-07,  2.35604853e-06, -1.75716252e-06],
        [-1.19209290e-07, -6.90033630e-08,  1.23166444e-07],
        [-3.99351120e-06,  3.39080270e-06,  6.54668156e-07],
        [-1.07288361e-06,  5.33181151e-07,  4.79330993e-07],
        [-1.29938126e-05,  8.65719176e-06,  4.26166844e-06],
        [-1.16782784e-02,  7.17897015e-03,  4.49936884e-03],
        [ 2.56299973e-06,  2.18188452e-05, -2.43150153e-05],
        [ 1.10864639e-05, -1.29933796e-05,  1.99464762e-06],
        [-5.18560410e-06,  1.17952754e-06,  4.02244586e-06],
        [ 5.18560410e-06, -3.63211120e-06, -1.45230797e-06],
        [-2.32458115e-06,  1.92265838e-06,  3.99702117e-07],
        [ 2.49743462e-05, -1.05908148e-05, -1.44097285e-05],
        [-3.27825546e-06,  2.16029048e-06,  1.07683627e-06],
        [ 1.28149986e-05, -5.03027468e-06, -7.79932816e-06],
        [ 9.53674316e-07, -1.21630183e-06,  2.28703357e-07],
        [ 0.00000000e+00,  3.29973955e-06, -3.40002862e-06]]],
      dtype=float32)`

Some numbers are negative. Does it mean "donor or acceptor lose"? I may understand wrongly. The numbers still look like probability instead of delta-score.

When I do this, I get nothing:
`acceptor_prob = delta[0, :, 1]`

How do I get scores similar to the .vcf output file from running SpliceAI?

Thanks,
Woody

**Comment by kishorejaganathan** [comment]
The delta score logic only applies for variants. This case is a bit tricky since the two sequences differ at multiple positions. If there is one-to-one correspondence between the ref and alt sequence, then np.max(delta[0, :, 1]), -np.min(delta[0, :, 1]), np.max(delta[0, :, 2]), -np.min(delta[0, :, 2]) gives you DS_AG, DS_AL, DS_DG, DS_DL respectively. This case seems to be an MNV where REF size is 4 and ALT size is 3. You can condense the 4 values of REF into one value via max, and similarly the 3 values of ALT into one value via max so that you have one-to-one correspondence between the outputs for REF and ALT, and then apply the transformations mentioned in the beginning of this post.

**Comment by wososa** [comment]
If I only substitute two nucleotides (TA->AT):

`alt = 'CGATCTGACGTGGGTGTCATCGCATTATCGATATTGCAT'`
`ref = 'CGATCTGACGTGGGTGTCATCGCATATTCGATATTGCAT'`
`context = 10000`
`paths = ('models/spliceai{}.h5'.format(x) for x in range(1, 6))`
`models = [load_model(resource_filename('spliceai', x)) for x in paths]`
`x1 = one_hot_encode('N'*(context//2) + alt + 'N'*(context//2))[None, :]`
`x2 = one_hot_encode('N'*(context//2) + ref + 'N'*(context//2))[None, :]`
`delta = np.mean([models[m].predict(x2) for m in range(5)], axis=0) - np.mean([models[m].predict(x1) for m in range(5)], axis=0)`

Can I still use `np.max(delta[0, :, 1]), -np.min(delta[0, :, 1]), np.max(delta[0, :, 2]), -np.min(delta[0, :, 2])`?

Thanks,
Woody

**Comment by kishorejaganathan** [comment]
Yes

**Comment by wososa** [comment]
Hi @kishorejaganathan ,

Thanks for your reply. The values don't look like delta-score (range 0~1). Is it supposed to be like `6.1841347e-06` kind of number?

Best,
Woody

**Comment by kishorejaganathan** [comment]
Most variants don't do anything, so the numbers are expected to be low. We round the delta scores to 4 decimal places, so this number would appear as 0.

**Comment by wososa** [comment]
Hi @kishorejaganathan ,

How long should the input sequence be? Should it be the whole chromosome? or the sequence of the gene region? or +-1000bp of target exon?

Thanks,
Woody

**Comment by kishorejaganathan** [comment]
+-5000 bp of the target exon

**Comment by wososa** [comment]
Hi @kishorejaganathan ,

I tried to use +-5000bp of the target exon, but I got different delta scores. Is this normal? For example,

`Use +-5000bp custom sequence`
DS_AG = 0.0505
DS_AL = 0.0000
DS_DG = 0.0390
DS_DL = 0.0091

`Use spliceai -I test.vcf -O output.vcf`
DS_AG = 0.00
DS_AL = 0.00
DS_DG = 0.00
DS_DL = 0.14

I don't know how to get `DP_AG|DP_AL|DP_DG|DP_DL` for custom sequence, so I might be doing the wrong comparison. Could you please show me how to get `DP_AG|DP_AL|DP_DG|DP_DL` from custom sequence?

Thanks,
Woody

**Comment by kishorejaganathan** [comment]
Changing max to argmax in the equation will give you the DP values. The SpliceAI output should match with whatever you're calculating if the sequence is borrowed from the reference genome with the setting -D 5000 (the default value for -D is 50).

**Comment by wososa** [comment]
@kishorejaganathan ,

Thanks again for quick reply. I got DP numbers like this:

DP_AG = 4999.0000
DP_AL = -5103.0000
DP_DG = 5052.0000
DP_DL = -5103.0000

1. The DP_AG numbers mean the 4999th nucleotides of the input sequence, right? DP_AL means the 5103th nucleotide from the end of the input sequence?

2. If I only care about 50bp around the target exon, should I use -D 50 and use only sequence within +-50 as input sequence? 

Thanks,
Woody

**Comment by kishorejaganathan** [comment]
No... DP corresponds to the distance between the variant position and the position where splicing changes the most. These values are interesting only when DS is high enough (strength of splicing change). DS is the result of an np.max operation and DP is the result of the corresponding argmax operation essentially. Such large values for DP generally means DS is close to 0 and the argmax returns a random position pretty much.

-D parameter decides how far from the variant you will be looking for splicing changes.
