### ISSUE TITLE
indel or snv problem.

### ISSUE THREAD

**Issue by summerghw** [Illumina/SpliceAI#77]
hello:
1.I have find a database that created by SpliceAI, but variation which is indel or snv are not in this database.  but i can use spliceai to get score form these kind of variation. my question is does these variation need to score by spliceai.  i

2.another question is  when i fix the parameter "maximum distance between the variant and gained/lost splice site, defaults to 50" to a lager scale like 10k  which was most accuracy said in the article. sometimes there will be more than one splice site score. is that normal ?

3.last question is that some tools like netgene2, nnsplice, fsplice , MaxEntScan,GeneSplicer, are they replaced by spliceai or they can be supplement. because i found they were invent long time ago and not easy to large-scale use.

thank you very much.

**Comment by kishorejaganathan** [comment]
1. Yeah you can use SpliceAI to score variants that are not provided in the database. This is typically the case when you are interested in the scores of long indels.
2. Yes, that is normal. For events like exon skipping, you will see that the variant affects both the acceptor and donor. This will result in two scores. You can take the maximum of the two scores if you want just a single score.
3. You can replace the older tools with SpliceAI as it is far more accurate.
