### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by nikigogate** [Illumina/SpliceAI#81]
I am trying to run the example file. I am using it through Anaconda. 

Here is the error I am getting: 
(miniconda3) bash-3.2$ spliceai -I /Users/X/SpliceAI/examples/input.vcf -O output_1.vcf -R /Users/X/Refs/hg38.fa -A grch38

Using TensorFlow backend.

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_qint8 = np.dtype([("qint8", np.int8, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_qint16 = np.dtype([("qint16", np.int16, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_qint32 = np.dtype([("qint32", np.int32, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  np_resource = np.dtype([("resource", np.ubyte, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_qint8 = np.dtype([("qint8", np.int8, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_qint16 = np.dtype([("qint16", np.int16, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  _np_qint32 = np.dtype([("qint32", np.int32, 1)])

/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

  np_resource = np.dtype([("resource", np.ubyte, 1)])

Traceback (most recent call last):

  File "/Users/X/.conda/envs/miniconda3/bin/spliceai", line 10, in <module>

    sys.exit(main())

  File "/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/spliceai/__main__.py", line 69, in main

    ann = Annotator(args.R, args.A)

  File "/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/spliceai/utils.py", line 44, in __init__

    self.models = [load_model(resource_filename(__name__, x)) for x in paths]

  File "/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/spliceai/utils.py", line 44, in <listcomp>

    self.models = [load_model(resource_filename(__name__, x)) for x in paths]

  File "/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper

    return load_function(*args, **kwargs)

  File "/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 584, in load_model

    model = _deserialize_model(h5dict, custom_objects, compile)

  File "/Users/X/.conda/envs/miniconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 273, in _deserialize_model

    model_config = json.loads(model_config.decode('utf-8'))

**AttributeError: 'str' object has no attribute 'decode'**

Please help!

**Comment by kishorejaganathan** [comment]
This is likely due to version mismatch issues. Could you please let me know the versions of Keras, Tensorflow and h5py that you are using? The solution is to downgrade one of them, not immediately sure which one.

**Comment by jliang28** [comment]
Hi! I am also having the same issue. My version of Keras is 2.3.1, version of Tensorflow is 2.0.0, version of h5py is 3.2.1. 

Thanks for your help!

**Comment by kishorejaganathan** [comment]
Could you try downgrading h5py to version 2.10.0 and see if that solves the issue?

**Comment by jliang28** [comment]
That worked! However, now I am getting a warning (See below) that says no training configuration found. When I use the provided input file in the examples directory, I get an empty output file. 

This is the command that I am running: `spliceai -I examples/input.vcf -O output.vcf -R hg19.fa -A grch37`


Warnings generated: 

Using TensorFlow backend.

2021-08-30 16:26:23.277352: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.

2021-08-30 16:26:23.277913: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 12. Tune using inter_op_parallelism_threads for best performance.

/Users/X/anaconda3/envs/X/lib/python3.7/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

**Comment by kishorejaganathan** [comment]
Those warnings are benign, you can safely ignore them. This should really work, are the contents of the output.vcf file completely empty (i.e., not even a header)?

**Comment by jliang28** [comment]
Yep, I checked the file and it was completely empty.

**Comment by kishorejaganathan** [comment]
Hmm, that's very surprising - not really sure what's going on. Your options are: Downgrade tensorflow to 1.9, or downgrade python to 3.6.

**Comment by jliang28** [comment]
Ah for some reason, if I pip the input and output files, I get the correct output. However, if I use `spliceai -I input.vcf -O output.vcf -R genome.fa -A grch37`, I am still getting an empty output file. (Also, I tried this with both downgrading the packages and not downgrading the packages). 

Thank you so much for your help in figuring this out! :)

**Comment by amootta** [comment]
Hi, sorry to open up an old issue. I've been having the same problems with running the programme. I'm on python 3.7 - have keras v.2.3.1, Tensorflow v.1.9.0 and h5py version 2.10.0. I am getting the same error: 
Using TensorFlow backend.
2021-11-08 21:50:22.893413: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-08 21:50:22.904246: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000000000 Hz
2021-11-08 21:50:22.906847: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55cf098c7c50 executing computations on platform Host. Devices:
2021-11-08 21:50:22.906882: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2021-11-08 21:50:22.915940: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
/home/am3u20/.conda/envs/spliceai_3.7/lib/python3.7/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.

I've trialled it with the example input.vcf provided, and the output basically has no annotations as is to be expected in the example output provided. Please let me know what else I can try to fix this error! Thanks very much
