### ISSUE TITLE
Implementaion of SpliceAI without a input VCF

### ISSUE THREAD

**Issue by wigge206** [Illumina/SpliceAI#83]
Hi, 
Is it possible to use spiceAI on a list of variants rather than VCF. I have data of observed splicing events by a range of variants and we want to see how well SpliceAI would have predicted these events. 

Alternatively, any tips on manually generating VCF files from a list of variants with CHR POS REF ALT

**Comment by kishorejaganathan** [comment]
Reformatting a list into a VCF is very straightforward. Just copy paste a header from any VCF file (examples/input.vcf for instance, if you're using hg19, or an equivalent one if you're using hg38). The rest should be achievable with a single line awk command.
