### ISSUE TITLE
Which training dataset was used for PyPI SpliceAI model?

### ISSUE THREAD

**Issue by shiro-kur** [Illumina/SpliceAI#85]
Hi,

I would like to ask about training dataset.

I read SpliceAI article and found you tried two training dataset, "Canonical" and "plus GTEx" ones. 

Which dataset was used for the distributed SpliceAI model on PyPI??

**Comment by kishorejaganathan** [comment]
plus GTEx

**Comment by shiro-kur** [comment]
Thanks!!
