### ISSUE TITLE
 Very slow prediction speed

### ISSUE THREAD

**Issue by fo40225** [Illumina/SpliceAI#9]
GPU utilization is low, please optimize it.

Try to reduce the times of prediction, each call should have bunch of data.

**Comment by kishorejaganathan** [comment]
To make life easier for users, we have already precomputed the scores for all possible SNVs within genes and provided it as supplemental data with the paper (you can also find the link for it in the README file). So, you need this software only to score INDELs, which should hopefully be a manageable task.
