### ISSUE TITLE
limit the CPU of SpliceAI?

### ISSUE THREAD

**Issue by zofieLin** [Illumina/SpliceAI#93]
Hi, are there any methods to limit the CPU of SpliceAI? 
I am running SpliceAI (spliceai==1.3.1) with PBS on linux cluster, the command line is like below
`spliceai -I input.vcf -O output.vcf -A grch37 -R refseq `
but then the jobs always be killed by exceeded limit of CPU.

My input just contained around 1,000 variants, but it seems to require very large CPU, jobs were killed even if the CPU setting is 10 or 12.
I also tried `export OMP_NUM_THREADS=4`  in my bash script or `OMP_NUM_THREADS=4 spliceai`, but it didn't help.
Are there any solutions?

Thanks!

_Originally posted by @zofieLin in https://github.com/Illumina/SpliceAI/issues/20#issuecomment-982722416_

**Comment by kishorejaganathan** [comment]
I have tested the following solution successfully: Please add the lines 

```
from keras import backend as K
K.set_session(K.tf.Session(config=K.tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)))

```
to the top of your copy of spliceai/utils.py and you should be set. Let me know if you still have issues.
