### ISSUE TITLE
AttributeError: 'str' object has not attribute 'decode'

### ISSUE THREAD

**Issue by AGunnell77** [Illumina/SpliceAI#95]
HI
I am getting this error when trying to run the example data or my own file:

File "/home/agunnell/.conda/envs/SpliceAI/lib/python3.7/site-packages/keras/en                                                                             gine/saving.py", line 273, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

**Comment by dyw77030** [comment]
I'm running into the error trying to run the script under
**3. Can SpliceAI be used to score custom sequences?**

**Comment by kishorejaganathan** [comment]
Can you try downgrading h5py to version 2.10.0 if that is not already the case? If that does not solve the problem, downgrading Keras to 2.3 and Tensorflow to 1.9 are other options. Let me know if these solutions do not solve the issue.

**Comment by AGunnell77** [comment]
Hi I downgraded to  h5py version 2.10.0, Keras version 2.3.1 and Tensorflow version 1.9.0 and got different errors which appeared similar to a previous post which suggested downgrading to python version 3.6. After this I got the following:

 File "/home/agunnell/.conda/envs/SpliceAI/bin/spliceai", line 12, in <module>
    sys.exit(main())
  File "/home/agunnell/.conda/envs/SpliceAI/lib/python3.6/site-packages/spliceai/__main__.py", line 53, in main
    ann = Annotator(args.R, args.A)
  File "/home/agunnell/.conda/envs/SpliceAI/lib/python3.6/site-packages/spliceai/utils.py", line 20, in __init__
    self.genes = df['#NAME'].get_values()
  File "/home/agunnell/.conda/envs/SpliceAI/lib/python3.6/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'get_values'

Thanks

**Comment by kishorejaganathan** [comment]
Can you try with keras==2.0.5, tensorflow==1.9.0, h5py==2.10.0 in python 3.6? This issue you're facing is due to pandas deprecating a function used by SpliceAI. Can you try python 2.7 and pandas 0.24 if you still have issues?

**Comment by AGunnell77** [comment]
Hi the suggested changes in python3.6 did not work. When trying to install python2.7 there was a long list of conflicts. Trying pandas 0.24 with python 3.6 the error changed to this:
File "/home/agunnell/.conda/envs/SpliceAI/lib/python3.6/site-packages/theano/gof/cc.py", line 1350, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: ('The following error happened while compiling the node', DotModulo(A, s, m, A2, s2, m2), '\n', "module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'")

**Comment by AGunnell77** [comment]
I have this working now thanks.

**Comment by KunFang93** [comment]
> I have this working now thanks.

Hi, 

I wondered if you could give any hints of solutions? I got the same errors. Thanks~

Kun
