### ISSUE TITLE
hg19/hg38 

### ISSUE THREAD

**Issue by AGunnell77** [Illumina/SpliceAI#96]
My vcf file with hg19 co-ordinates only runs if I use the hg38.fa and grch38.txt file. Having used liftover to give a vcf with hg38 co-ordinates it will then only run with the hg19.fa and grch37 .txt file! I have double checked my vcf build with SNP IDS on the UCSC genome browser and used the  SpliceAI lookup for a number of SNPs and confirm different results from the runs with the wrong builds.

**Comment by kishorejaganathan** [comment]
This is unusual, can you explain more what you mean by "only run"? What happens when you provide the vcf with the correct genome build? As debugging steps, can you double check the header of the VCF as well as whether the genomes are actually of the build indicated by their file names?

**Comment by AGunnell77** [comment]
Thank you. I think it was a problem with the vcf header.
